const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(+n||0), iso=(d=new Date())=>d.toISOString().slice(0,10), ym=()=>iso().slice(0,7), id=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2);
const defaultState={profile:{name:'ZAZOHAN',motto:'HER GÜN BİR ADIM.'},settings:{dailyRate:1500,hourlyRate:250,overtimeRate:350},work:[],expenses:[],incomes:[],notes:[],accounts:{card:{name:'KREDİ KARTI',balance:0,limit:0},flex:{name:'ESNEK HESAP',balance:0,limit:0}},investments:[]};
let state=JSON.parse(localStorage.getItem('rutin-v1')||'null')||defaultState, tab='home', modal=null, reportPeriod='month';
const save=()=>localStorage.setItem('rutin-v1',JSON.stringify(state));
const todayWork=()=>state.work.filter(x=>x.date===iso());
const monthFilter=a=>a.filter(x=>x.date?.startsWith(ym()));
function totals(){let inc=state.incomes.filter(x=>x.date.startsWith(ym())).reduce((a,x)=>a+x.amount,0),exp=monthFilter(state.expenses).reduce((a,x)=>a+x.amount,0);for(const w of monthFilter(state.work)){if(w.type==='daily')inc+=w.amount||state.settings.dailyRate;if(w.type==='hourly')inc+=(w.hours||0)*(w.rate||state.settings.hourlyRate);if(w.type==='overtime')inc+=(w.hours||0)*(w.rate||state.settings.overtimeRate)}return{inc,exp,net:inc-exp}}
function top(){return`<div class="top"><div></div><div class="brand">RUTİN</div><button class="iconBtn" onclick="openModal('profile')">⚙</button></div>`}
function home(){let T=totals(), tw=todayWork();return`${top()}<div class="hero"><div class="avatar">Z</div><div><small>MERHABA</small><h2>${state.profile.name}</h2><div class="date">${new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div></div></div>
<div class="quote"><b>GÜNÜN SÖZÜ</b><div>“${state.profile.motto}”</div></div>
<div class="grid4"><div class="stat"><small>BU AY KAZANÇ</small><strong class="green">${money(T.inc)}</strong></div><div class="stat"><small>BU AY HARCAMA</small><strong class="red">${money(T.exp)}</strong></div><div class="stat"><small>İŞ MASRAFI</small><strong class="gold">${money(monthFilter(state.expenses).filter(x=>x.workCost).reduce((a,x)=>a+x.amount,0))}</strong></div><div class="stat"><small>NET KALAN</small><strong>${money(T.net)}</strong></div></div>
<div class="section"><b>BUGÜN ÇALIŞMA</b><span>${tw.length?'KAYIT VAR':'KAYIT YOK'}</span></div><div class="workToday"><button class="workBtn" onclick="workedToday()">✓ BUGÜN ÇALIŞTIM</button><button class="workBtn secondary" onclick="openModal('hourly')">SAATLİK ÇALIŞMA</button></div><button class="workBtn" style="width:100%;margin-top:8px" onclick="openModal('overtime')">+ MESAİ EKLE</button>
<div class="section"><b>HIZLI İŞLEMLER</b></div><div class="actions"><button class="action" onclick="openModal('expense')"><i>−</i>HARCAMA</button><button class="action" onclick="openModal('income')"><i>+</i>GELİR</button><button class="action" onclick="openModal('note')"><i>✎</i>NOT</button><button class="action" onclick="tab='calendar';render()"><i>▦</i>TAKVİM</button></div>
<div class="section"><b>SON HAREKETLER</b></div><div class="card list">${recentRows()}</div>`}
function recentRows(){let a=[...state.expenses.map(x=>({...x,k:'expense'})),...state.incomes.map(x=>({...x,k:'income'})),...state.work.map(x=>({...x,k:'work'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);return a.length?a.map(x=>`<div class="row"><div class="ico">${x.k==='expense'?'−':x.k==='income'?'+':'⌁'}</div><div><b>${x.title||({daily:'GÜNLÜK ÇALIŞMA',hourly:'SAATLİK ÇALIŞMA',overtime:'MESAİ'}[x.type]||'KAYIT')}</b><small>${x.date}${x.hours?' · '+x.hours+' SAAT':''}</small></div><div class="amount ${x.k==='expense'?'red':x.k==='income'?'green':'gold'}">${x.k==='expense'?'-':x.k==='income'?'+':''}${x.amount?money(x.amount):''}</div></div>`).join(''):'<div class="muted">Henüz kayıt yok.</div>'}
function work(){let m=monthFilter(state.work),daily=m.filter(x=>x.type==='daily').length,hourly=m.filter(x=>x.type==='hourly'),ot=m.filter(x=>x.type==='overtime');return`${top()}<div class="section"><b>ÇALIŞMA</b><span>${ym()}</span></div><div class="grid4"><div class="stat"><small>GÜNLÜK</small><strong class="green">${daily} GÜN</strong></div><div class="stat"><small>SAATLİK</small><strong class="blue">${hourly.reduce((a,x)=>a+(x.hours||0),0)} SAAT</strong></div><div class="stat"><small>MESAİ</small><strong class="gold">${ot.reduce((a,x)=>a+(x.hours||0),0)} SAAT</strong></div><div class="stat"><small>ÇALIŞMA KAYDI</small><strong>${m.length}</strong></div></div><div class="section"><b>KAYIT EKLE</b></div><div class="actions" style="grid-template-columns:repeat(3,1fr)"><button class="action" onclick="workedToday()"><i>✓</i>ÇALIŞTIM</button><button class="action" onclick="openModal('hourly')"><i>◷</i>SAATLİK</button><button class="action" onclick="openModal('overtime')"><i>★</i>MESAİ</button></div><div class="section"><b>BU AY</b></div><div class="card list">${m.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="row"><div class="ico">${x.type==='daily'?'✓':x.type==='hourly'?'◷':'★'}</div><div><b>${x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ'}</b><small>${x.date}${x.hours?' · '+x.hours+' SAAT':''}</small></div><div class="amount gold">${money(x.amount||((x.hours||0)*(x.rate||0)))}</div></div>`).join('')||'<div class="muted">Kayıt yok.</div>'}</div>`}
function finance(){let T=totals();return`${top()}<div class="section"><b>FİNANS</b></div><div class="grid4"><div class="stat"><small>KREDİ KARTI BORCU</small><strong class="red">${money(state.accounts.card.balance)}</strong></div><div class="stat"><small>ESNEK HESAP</small><strong class="red">${money(state.accounts.flex.balance)}</strong></div><div class="stat"><small>YATIRIM</small><strong class="green">${money(state.investments.reduce((a,x)=>a+x.amount,0))}</strong></div><div class="stat"><small>NET AYLIK</small><strong>${money(T.net)}</strong></div></div><div class="section"><b>İŞLEMLER</b></div><div class="actions"><button class="action" onclick="openModal('expense')"><i>−</i>HARCAMA</button><button class="action" onclick="openModal('income')"><i>+</i>GELİR</button><button class="action" onclick="openModal('investment')"><i>↗</i>YATIRIM</button><button class="action" onclick="openModal('accounts')"><i>▣</i>HESAPLAR</button></div><div class="section"><b>HAREKETLER</b></div><div class="card list">${recentRows()}</div>`}
function calendar(){let d=new Date(),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7, cells='';for(let i=0;i<offset;i++)cells+='<div></div>';for(let n=1;n<=days;n++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),cl=w.some(x=>x.type==='overtime')?'overtime':w.some(x=>x.type==='hourly')?'hourly':w.some(x=>x.type==='daily')?'daily':'off';cells+=`<div class="day ${cl}">${n}</div>`}return`${top()}<div class="section"><b>ÇALIŞMA TAKVİMİ</b><span>${d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}</span></div><div class="card"><div class="calendar">${cells}</div><div class="legend"><span><i class="dot" style="background:#315b40"></i>GÜNLÜK</span><span><i class="dot" style="background:#315a7c"></i>SAATLİK</span><span><i class="dot" style="background:#70592a"></i>MESAİ</span><span><i class="dot" style="background:#333"></i>ÇALIŞMADIM</span></div></div><div class="section"><b>AY ÖZETİ</b></div>${reportCards()}`}
function reportCards(){let m=monthFilter(state.work),daily=m.filter(x=>x.type==='daily').length,h=m.filter(x=>x.type==='hourly').reduce((a,x)=>a+(x.hours||0),0),o=m.filter(x=>x.type==='overtime').reduce((a,x)=>a+(x.hours||0),0),T=totals();return`<div class="grid4"><div class="stat"><small>ÇALIŞILAN GÜN</small><strong>${daily}</strong></div><div class="stat"><small>SAATLİK</small><strong class="blue">${h} SAAT</strong></div><div class="stat"><small>MESAİ</small><strong class="gold">${o} SAAT</strong></div><div class="stat"><small>NET</small><strong>${money(T.net)}</strong></div></div>`}
function reports(){let T=totals();return`${top()}<div class="section"><b>DETAYLI RAPOR</b></div><div class="tabs"><button>GÜN</button><button>HAFTA</button><button class="active">AY</button><button>YIL</button><button>TARİH ARALIĞI</button></div>${reportCards()}<div class="section"><b>GELİR / GİDER</b></div><div class="card"><div class="chart"><div class="bar g" style="height:${Math.min(100,T.inc/100)}%"></div><div class="bar r" style="height:${Math.min(100,T.exp/100)}%"></div></div><div class="legend"><span><i class="dot" style="background:#4c9c69"></i>GELİR ${money(T.inc)}</span><span><i class="dot" style="background:#a94d4d"></i>GİDER ${money(T.exp)}</span></div></div><div class="section"><b>NOTLAR</b><span onclick="openModal('note')">+ EKLE</span></div>${state.notes.slice().reverse().map(n=>`<div class="note"><b>${n.title}</b><p>${n.text}</p><small class="muted">${n.date}</small></div>`).join('')||'<div class="card muted">Henüz not yok.</div>'}`}
function nav(){return`<div class="nav">${[['home','⌂','ANA'],['work','⌁','ÇALIŞMA'],['finance','₺','FİNANS'],['calendar','▦','TAKVİM'],['reports','▥','RAPOR']].map(x=>`<button class="${tab===x[0]?'active':''}" onclick="tab='${x[0]}';render()"><i>${x[1]}</i>${x[2]}</button>`).join('')}</div>`}
function render(){let fn={home,work,finance,calendar,reports}[tab];$('#app').innerHTML=`<main class="app">${fn()}${nav()}</main>${modal?sheet(modal):''}`}
function workedToday(){if(state.work.some(x=>x.date===iso()&&x.type==='daily'))return alert('BUGÜNÜN GÜNLÜK ÇALIŞMA KAYDI ZATEN VAR.');state.work.push({id:id(),date:iso(),type:'daily',amount:state.settings.dailyRate,title:'GÜNLÜK ÇALIŞMA'});save();render()}
function openModal(k){modal=k;render()} function closeModal(){modal=null;render()}
const field=(n,l,v='',t='text')=>`<div class="field"><label>${l}</label><input name="${n}" value="${v}" type="${t}"></div>`;
function sheet(k){let title='',body='';if(k==='expense'){title='HARCAMA EKLE';body=`${field('title','AÇIKLAMA')}${field('amount','TUTAR','','number')}<div class="field"><label>KATEGORİ</label><select name="category"><option>YOL</option><option>YEMEK</option><option>MARKET</option><option>FATURA</option><option>DİĞER</option></select></div><div class="field"><label>ÖDEME</label><select name="method"><option>NAKİT</option><option>KREDİ KARTI</option><option>ESNEK HESAP</option></select></div><div class="field"><label>İŞ MASRAFI MI?</label><select name="workCost"><option value="0">HAYIR</option><option value="1">EVET</option></select></div>${field('date','TARİH',iso(),'date')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='income'){title='GELİR EKLE';body=`${field('title','AÇIKLAMA')}${field('amount','TUTAR','','number')}${field('date','TARİH',iso(),'date')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='hourly'){title='SAATLİK ÇALIŞMA';body=`${field('hours','BUGÜN KAÇ SAAT ÇALIŞTIN?','','number')}${field('rate','SAATLİK ÜCRET',state.settings.hourlyRate,'number')}${field('date','TARİH',iso(),'date')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='overtime'){title='MESAİ';body=`${field('hours','MESAİ SAATİ','','number')}${field('rate','MESAİ SAATLİK ÜCRET',state.settings.overtimeRate,'number')}${field('date','TARİH',iso(),'date')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='note'){title='NOT EKLE';body=`${field('title','BAŞLIK')}<div class="field"><label>NOT</label><textarea name="text"></textarea></div><button class="btn goldBtn">KAYDET</button>`}
if(k==='investment'){title='YATIRIM EKLE';body=`${field('title','YATIRIM ADI')}${field('amount','TUTAR','','number')}${field('date','TARİH',iso(),'date')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='accounts'){title='HESAPLAR';body=`${field('cardBalance','KREDİ KARTI BORCU',state.accounts.card.balance,'number')}${field('cardLimit','KREDİ KARTI LİMİTİ',state.accounts.card.limit,'number')}${field('flexBalance','ESNEK HESAP BORCU',state.accounts.flex.balance,'number')}${field('flexLimit','ESNEK HESAP LİMİTİ',state.accounts.flex.limit,'number')}<button class="btn goldBtn">KAYDET</button>`}
if(k==='profile'){title='PROFİL & AYARLAR';body=`${field('name','AD',state.profile.name)}${field('motto','MOTTO',state.profile.motto)}${field('dailyRate','GÜNLÜK ÜCRET',state.settings.dailyRate,'number')}${field('hourlyRate','SAATLİK ÜCRET',state.settings.hourlyRate,'number')}${field('overtimeRate','MESAİ SAATLİK ÜCRET',state.settings.overtimeRate,'number')}<button class="btn goldBtn">KAYDET</button>`}
return`<div class="sheetWrap" onclick="if(event.target===this)closeModal()"><form class="sheet" onsubmit="submitForm(event,'${k}')"><div class="sheetHead"><b>${title}</b><button type="button" class="close" onclick="closeModal()">×</button></div>${body}</form></div>`}
function submitForm(e,k){e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget).entries());if(k==='expense')state.expenses.push({id:id(),title:(d.title||d.category).toUpperCase(),amount:+d.amount||0,category:d.category,method:d.method,workCost:d.workCost==='1',date:d.date});if(k==='income')state.incomes.push({id:id(),title:(d.title||'GELİR').toUpperCase(),amount:+d.amount||0,date:d.date});if(k==='hourly')state.work.push({id:id(),title:'SAATLİK ÇALIŞMA',type:'hourly',hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),date:d.date});if(k==='overtime')state.work.push({id:id(),title:'MESAİ',type:'overtime',hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),date:d.date});if(k==='note')state.notes.push({id:id(),title:(d.title||'NOT').toUpperCase(),text:d.text||'',date:iso()});if(k==='investment')state.investments.push({id:id(),title:(d.title||'YATIRIM').toUpperCase(),amount:+d.amount||0,date:d.date});if(k==='accounts'){state.accounts.card.balance=+d.cardBalance||0;state.accounts.card.limit=+d.cardLimit||0;state.accounts.flex.balance=+d.flexBalance||0;state.accounts.flex.limit=+d.flexLimit||0}if(k==='profile'){state.profile.name=(d.name||'ZAZOHAN').toUpperCase();state.profile.motto=(d.motto||'').toUpperCase();state.settings.dailyRate=+d.dailyRate||0;state.settings.hourlyRate=+d.hourlyRate||0;state.settings.overtimeRate=+d.overtimeRate||0}save();modal=null;render()}
render(); if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
