/* RUTİN CLEAN V2 — 12 maddelik kilit paket yükseltmesi */
(function(){
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const catMeta={
 'YOL':['⌁','road'], 'YEMEK':['◉','food'], 'MARKET':['▣','market'], 'FATURA':['▤','bill'], 'KİRA':['⌂','rent'],
 'SAĞLIK':['♡','health'], 'ULAŞIM':['◈','transport'], 'EĞLENCE':['★','fun'], 'YAKIT':['◒','fuel'], 'GİYİM':['♢','wear'],
 'HARÇLIK':['₺','allowance'], 'FIRIN':['♨','bakery'], 'DİĞER':['•••','other']
};
function migrate(){
 state.work=Array.isArray(state.work)?state.work:[]; state.expenses=Array.isArray(state.expenses)?state.expenses:[];
 state.incomes=Array.isArray(state.incomes)?state.incomes:[]; state.investments=Array.isArray(state.investments)?state.investments:[];
 state.cards=Array.isArray(state.cards)?state.cards:[]; state.flexAccounts=Array.isArray(state.flexAccounts)?state.flexAccounts:[];
 state.manualReminders=Array.isArray(state.manualReminders)?state.manualReminders:[];
 state.reminderDismissed=state.reminderDismissed&&typeof state.reminderDismissed==='object'?state.reminderDismissed:{};
 state.cashTransactions=Array.isArray(state.cashTransactions)?state.cashTransactions:[];
 state.accounts=state.accounts||{}; state.accounts.cash=state.accounts.cash||{name:'NAKİT',balance:0};
 if(!state.cashTransactions.length && (+state.accounts.cash.balance||0)!==0) state.cashTransactions.push({id:uid(),type:'add',amount:+state.accounts.cash.balance||0,title:'DEVREDEN NAKİT',date:iso()});
 state.categories=Array.from(new Set([...(Array.isArray(state.categories)?state.categories:[]),'YOL','YEMEK','MARKET','FATURA','KİRA','SAĞLIK','ULAŞIM','EĞLENCE','YAKIT','GİYİM','HARÇLIK','FIRIN','DİĞER']));
 state.cards.forEach(c=>{c.transactions=Array.isArray(c.transactions)?c.transactions:[]; c.statementDate=c.statementDate||''; c.dueDate=c.dueDate||'';});
 state.flexAccounts.forEach(c=>{c.transactions=Array.isArray(c.transactions)?c.transactions:[]; c.statementDate=c.statementDate||''; c.dueDate=c.dueDate||'';});
 // Eski çalışma-yol kayıtlarını mümkün olduğunca ilgili işe bağla.
 state.work.forEach(w=>{
   if(w.roadExpenseId && !state.expenses.some(e=>e.id===w.roadExpenseId)) w.roadExpenseId='';
   if(!w.roadExpenseId){
     const r=state.expenses.find(e=>!e.workId&&e.date===w.date&&(e.category==='YOL'||e.title==='YOL')&&String(e.note||'').includes('ÇALIŞMA YOL'));
     if(r){r.workId=w.id;w.roadExpenseId=r.id;}
   }
 });
 save();
}
migrate();

function workAmount(x){return x.type==='daily'?(+x.amount||state.settings.dailyRate):(+x.hours||0)*(+x.rate||0)}
function roadForWork(id){return state.expenses.find(e=>e.workId===id && (e.category==='YOL'||e.sourceType==='workRoad'))||null}
function expenseMeta(x){return catMeta[x.category]||catMeta['DİĞER']}
function actionButtons(kind,id,ds=''){
 const edit=`openModal('editRecord:${kind}:${id}${ds?':'+ds:''}')`;
 const del=`deleteRecord('${kind}','${id}','${ds}')`;
 return `<div class="rowActions"><button class="miniEdit" onclick="${edit}">DÜZENLE</button><button class="miniDelete" onclick="${del}">SİL</button></div>`;
}

header=function(title='RUTİN',back=false){
 return `<div class="topbar premiumTopbar">
   <button class="iconBtn luxuryIconBtn" onclick="${back?"go('home')":"openModal('menu')"}">${back?'‹':'☰'}</button>
   <div class="title brandTitle">${title==='RUTİN'?`${rutinLogo(30)}<span>RUTİN</span>`:title}</div>
   <div class="topRightStack"><button class="iconBtn luxuryIconBtn settingsOnly" onclick="go('settings')" aria-label="Ayarlar"><span class="settingsGearV27">⚙</span></button><button class="iconBtn luxuryIconBtn reminderTopBtn" onclick="openModal('reminderCenter')" aria-label="Hatırlatma">◔</button></div>
 </div>`;
};

function activeReminders(){
 const out=[], today=iso(), todayD=new Date(today+'T12:00:00'), days=state.settings.reminderDays||2;
 for(const c of state.cards){if(c.dueDate){const diff=Math.ceil((new Date(c.dueDate+'T12:00:00')-todayD)/86400000);const id=`card:${c.id}:${c.dueDate}`;if(diff>=0&&diff<=days&&!state.reminderDismissed[id])out.push({id,title:`${c.name} SON ÖDEME`,detail:`${c.dueDate} · ${money(c.balance)}`,kind:'payment'});}}
 for(const c of state.flexAccounts){if(c.dueDate){const diff=Math.ceil((new Date(c.dueDate+'T12:00:00')-todayD)/86400000);const id=`flex:${c.id}:${c.dueDate}`;if(diff>=0&&diff<=days&&!state.reminderDismissed[id])out.push({id,title:`${c.name} ÖDEME`,detail:`${c.dueDate} · ${money(c.balance)}`,kind:'payment'});}}
 const hasWork=state.work.some(x=>x.date===today), hasExpense=state.expenses.some(x=>x.date===today);
 const autoId=`daily:${today}`;
 if(!state.reminderDismissed[autoId]&&(!hasWork||!hasExpense))out.push({id:autoId,title:'BUGÜNÜ TAMAMLA',detail:`${!hasWork?'Çalışma kaydı eksik. ':''}${!hasExpense?'Harcama kaydını kontrol et.':''}`,kind:'task'});
 for(const r of state.manualReminders.filter(x=>!x.done)){
   if(!r.date||r.date<=today)out.push({id:`manual:${r.id}`,title:r.title,detail:r.date||'MANUEL HATIRLATMA',kind:'manual',rid:r.id});
 }
 return out;
}
function reminderCards(){const a=activeReminders();if(!a.length)return'';return `<div class="homeReminderStack">${a.slice(0,3).map(r=>`<div class="homeReminderCard"><div><b>${esc(r.title)}</b><small>${esc(r.detail)}</small></div><div class="reminderActions"><button onclick="completeReminder('${r.id}','${r.rid||''}')">${r.kind==='payment'?'ÖDEDİM':'YAPTIM'}</button><button onclick="dismissReminder('${r.id}')">×</button></div></div>`).join('')}</div>`}
completeReminder=function(id,rid=''){if(rid){const r=state.manualReminders.find(x=>x.id===rid);if(r)r.done=true;}state.reminderDismissed[id]=true;save();render()}
dismissReminder=function(id){state.reminderDismissed[id]=true;save();render()}
submitManualReminder=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());state.manualReminders.push({id:uid(),title:upper(d.title||'HATIRLATMA'),date:d.date||iso(),done:false});save();modal='reminderCenter';render()}
deleteManualReminder=function(id){state.manualReminders=state.manualReminders.filter(x=>x.id!==id);save();modal='reminderCenter';render()}

home=function(){
 const T=monthlyTotals();
 return `${header()}${profileLine()}${reminderCards()}
 <div class="heroMsg"><b>${greetingByTime()}!</b><br>${dailyQuote()}</div>
 <div class="stats"><div class="stat"><small>BUGÜNKÜ GELİR</small><strong class="green">${money(todayIncome())}</strong></div><div class="stat"><small>BUGÜNKÜ HARCAMA</small><strong class="red">${money(todayExpense())}</strong></div><div class="stat"><small>BU AY GELİR</small><strong class="green">${money(T.income)}</strong></div><div class="stat"><small>BU AY HARCAMA</small><strong class="red">${money(T.expense)}</strong></div></div>
 <div class="section"><b>HIZLI İŞLEMLER</b></div><div class="quick quickPremium quickSix">
 <button onclick="openModal('income')"><i class="luxGlyph">＋</i><span>GELİR EKLE</span></button><button onclick="go('expenses')"><i class="luxGlyph">▤</i><span>HARCAMALAR</span></button><button onclick="openModal('daily')"><i class="luxGlyph">✓</i><span>ÇALIŞTIM</span></button><button onclick="go('notes')"><i class="luxGlyph">✦</i><span>NOTLAR</span></button><button onclick="go('investments')"><i class="luxGlyph">◇</i><span>YATIRIM</span></button><button onclick="go('finance')"><i class="luxGlyph">▣</i><span>FİNANS</span></button></div>
 <div class="section"><b>BUGÜNÜN ÖZETİ</b><span onclick="openModal('day:${iso()}')">AÇ / DÜZENLE ›</span></div>
 <div class="summaryBox clickableSummary" onclick="openModal('day:${iso()}')">
 ${sumRow('ÇALIŞMA',state.work.filter(x=>x.date===iso()&&x.type==='daily').length+' GÜN')}${sumRow('SAATLİK',state.work.filter(x=>x.date===iso()&&x.type==='hourly').reduce((a,x)=>a+(+x.hours||0),0)+' SAAT')}${sumRow('MESAİ',state.work.filter(x=>x.date===iso()&&x.type==='overtime').reduce((a,x)=>a+(+x.hours||0),0)+' SAAT')}${sumRow('TOPLAM KAZANÇ',money(todayIncome()))}${sumRow('TOPLAM HARCAMA',money(todayExpense()))}</div>`;
};

function expenseFormFor(x=null){
 const sel=x?.category||'YOL';
 return `<form onsubmit="${x?`submitEditExpense(event,'${x.id}')`:'submitExpense(event)'}">${field('amount','TUTAR',x?.amount||0,'number')}
 <div class="field"><label>KATEGORİ</label><div class="categoryIcons">${Object.entries(catMeta).map(([c,[i,cl]])=>`<label class="catChip ${cl}"><input type="radio" name="category" value="${c}" ${c===sel?'checked':''} onchange="toggleOtherName(this.form)"><i>${i}</i><span>${c}</span></label>`).join('')}</div></div>
 <div class="field otherNameField" style="${sel==='DİĞER'?'':'display:none'}"><label>HARCAMA ADI</label><input name="customTitle" value="${esc(x?.customTitle||((x?.category==='DİĞER'&&x?.title!=='DİĞER')?x.title:''))}" placeholder="ÖRN. TAMİRAT"></div>
 <div class="field"><label>HESAPTAN</label><div class="payIcons"><label><input type="radio" name="method" value="NAKİT" ${(x?.method||'NAKİT')==='NAKİT'?'checked':''}><i>₺</i><span>NAKİT</span></label><label><input type="radio" name="method" value="KREDİ KARTI" ${x?.method==='KREDİ KARTI'?'checked':''}><i>▦</i><span>KREDİ KARTI</span></label><label><input type="radio" name="method" value="ESNEK HESAP" ${x?.method==='ESNEK HESAP'?'checked':''}><i>▥</i><span>ESNEK HESAP</span></label></div></div>
 ${field('date','TARİH',x?.date||iso(),'date')}<div class="field"><label>NOT</label><textarea name="note">${esc(x?.note||'')}</textarea></div><button class="primary">${x?'DEĞİŞİKLİĞİ KAYDET':'HARCAMAYI KAYDET'}</button></form>`;
}
toggleOtherName=function(f){const v=f.querySelector('[name=category]:checked')?.value;const el=f.querySelector('.otherNameField');if(el)el.style.display=v==='DİĞER'?'block':'none'}
expenseForm=function(){return expenseFormFor(null)};
submitExpense=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const category=d.category||'DİĞER',title=category==='DİĞER'?upper(d.customTitle||'DİĞER'):category;state.expenses.push({id:uid(),date:d.date,title,customTitle:category==='DİĞER'?title:'',amount:+d.amount||0,category,method:d.method||'NAKİT',note:d.note||''});save();modal=null;screen='expenses';render()};
submitEditExpense=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const x=state.expenses.find(z=>z.id===id);if(!x)return;const oldAmount=+x.amount||0,category=d.category||'DİĞER';Object.assign(x,{date:d.date,category,title:category==='DİĞER'?upper(d.customTitle||'DİĞER'):category,customTitle:category==='DİĞER'?upper(d.customTitle||''):'' ,amount:+d.amount||0,method:d.method||'NAKİT',note:d.note||''});if(x.sourceType==='card'&&x.cardId&&x.sourceId){const c=state.cards.find(z=>z.id===x.cardId),t=c?.transactions?.find(z=>z.id===x.sourceId);if(c&&t){c.balance=(+c.balance||0)+((+x.amount||0)-oldAmount);Object.assign(t,{title:x.title,amount:x.amount,date:x.date});}}save();closeModal();render()};
expensesScreen=function(){const a=state.expenses.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `${header('HARCAMALAR',true)}<div class="expenseHero"><div><small>BU AY HARCAMA</small><strong class="red">${money(monthItems(state.expenses).reduce((n,x)=>n+(+x.amount||0),0))}</strong></div><button class="premiumAddBtn" onclick="openModal('expense')"><i>＋</i><span>HARCAMA EKLE</span></button></div><div class="section"><b>HARCAMA DETAYLARI</b></div><div class="card list expenseList">${a.length?a.map(x=>{const [ic,cl]=expenseMeta(x);return `<div class="item expenseItem"><div class="ico expenseIco ${cl}">${ic}</div><div><b>${esc(x.title||x.category)}</b><small>${x.date} · ${esc(x.method||'NAKİT')}</small></div><div class="expenseRight"><div class="amt red">-${money(x.amount)}</div>${actionButtons('expense',x.id,x.date)}</div></div>`}).join(''):'<div class="notice">HENÜZ HARCAMA YOK.</div>'}</div>`};

function roadFields(x){const r=roadForWork(x.id);return `<div class="field"><label>YOL PARASI</label><div class="choiceRow"><label><input type="radio" name="road" value="yes" ${r?'checked':''}>ÖDEDİM</label><label><input type="radio" name="road" value="no" ${!r?'checked':''}>ÖDEMEDİM</label></div></div>${field('roadAmount','YOL TUTARI',r?.amount||0,'number')}`}
function syncRoad(work,d){let r=roadForWork(work.id);const want=d.road==='yes'&&(+d.roadAmount||0)>0;if(want){if(!r){r={id:uid(),workId:work.id,sourceType:'workRoad',category:'YOL',title:'YOL',method:'NAKİT',note:'ÇALIŞMA YOL MASRAFI'};state.expenses.push(r);}Object.assign(r,{date:work.date,amount:+d.roadAmount||0,workId:work.id});work.roadExpenseId=r.id;}else if(r){state.expenses=state.expenses.filter(e=>e.id!==r.id);work.roadExpenseId='';}}
submitDaily=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const w={id:uid(),type:'daily',date:d.date,title:upper(d.title||'ANA İŞ'),amount:+d.amount||0,note:d.note||''};state.work.push(w);syncRoad(w,d);save();closeModal();render()};
submitHourly=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const w={id:uid(),type:'hourly',date:d.date,title:upper(d.title||'EK İŞ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),note:d.note||''};state.work.push(w);syncRoad(w,d);save();closeModal();render()};
submitOvertime=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const w={id:uid(),type:'overtime',date:d.date,title:upper(d.title||'MESAİ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),note:d.note||''};state.work.push(w);save();closeModal();render()};
submitEditWork=function(e,id,fromDs=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const w=state.work.find(x=>x.id===id);if(!w)return;w.date=d.date;w.title=upper(d.title||w.title);w.note=d.note||'';if(w.type==='daily')w.amount=+d.amount||0;else{w.hours=+d.hours||0;w.rate=+d.rate||0;w.amount=w.hours*w.rate;}if(w.type!=='overtime')syncRoad(w,d);save();modal=`day:${w.date}`;render()};
deleteWork=function(id,ds=''){const r=roadForWork(id);state.work=state.work.filter(x=>x.id!==id);if(r)state.expenses=state.expenses.filter(x=>x.id!==r.id);save();modal=ds?`day:${ds}`:null;render()};
workRows=function(type){const a=state.work.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12);return a.length?a.map(x=>{const r=roadForWork(x.id);return `<div class="workRecord"><div class="item"><div class="ico">${type==='daily'?'✓':type==='hourly'?'◷':'★'}</div><div><b>${esc(x.title)}</b><small>${x.date}${x.hours?' · '+x.hours+' SAAT':''}</small></div><div class="amt gold">${money(workAmount(x))}</div></div>${r?`<div class="roadSub"><span>⌁ YOL ÜCRETİ · ${r.date}</span><b>${money(r.amount)}</b></div>`:''}<div class="recordActions">${actionButtons('work',x.id,x.date)}</div></div>`}).join(''):'<div class="notice">HENÜZ KAYIT YOK.</div>'};

function dayItems(ds){
 const items=[]; state.work.filter(x=>x.date===ds).forEach(x=>items.push({k:'work',x}));
 state.expenses.filter(x=>x.date===ds&&!x.workId).forEach(x=>items.push({k:'expense',x}));
 state.incomes.filter(x=>x.date===ds).forEach(x=>items.push({k:'income',x}));
 return items;
}
function dayModal(ds){const items=dayItems(ds);return `<div class="notice">BU GÜNÜN İŞ, MESAİ, HARCAMA, GELİR VE YOL KAYITLARINI BURADAN DÜZENLEYEBİLİRSİN.</div><div class="quick dayQuick"><button onclick="openModal('dailyDate:${ds}')"><i class="luxGlyph">✓</i>GÜNLÜK</button><button onclick="openModal('hourlyDate:${ds}')"><i class="luxGlyph">◷</i>SAATLİK</button><button onclick="openModal('overtimeDate:${ds}')"><i class="luxGlyph">✦</i>MESAİ</button><button onclick="openModal('expenseDate:${ds}')"><i class="luxGlyph">▤</i>HARCAMA</button></div><div class="card list dayFullList">${items.length?items.map(({k,x})=>{if(k==='work'){const r=roadForWork(x.id);return `<div class="dayRecord"><div class="item"><div class="ico">${x.type==='daily'?'✓':x.type==='hourly'?'◷':'✦'}</div><div><b>${esc(x.title)}</b><small>${x.type.toUpperCase()}${x.hours?' · '+x.hours+' SAAT':''}</small></div><div class="amt gold">${money(workAmount(x))}</div></div>${r?`<div class="roadSub"><span>⌁ YOL GİDERİ</span><b class="red">-${money(r.amount)}</b></div>`:''}${actionButtons('work',x.id,ds)}</div>`;} const [ic,cl]=k==='expense'?expenseMeta(x):['＋','income'];return `<div class="dayRecord"><div class="item"><div class="ico expenseIco ${cl}">${ic}</div><div><b>${esc(x.title)}</b><small>${k==='expense'?esc(x.category):'GELİR'}</small></div><div class="amt ${k==='expense'?'red':'green'}">${k==='expense'?'-':'+'}${money(x.amount)}</div></div>${actionButtons(k,x.id,ds)}</div>`}).join(''):'<div class="notice">BU GÜNDE KAYIT YOK.</div>'}</div>`}

calendarScreen=function(){
 const d=new Date(calendarCursor),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7;let cells='';for(let i=0;i<offset;i++)cells+='<div class="daySpacer premiumDaySpacer"></div>';
 for(let n=1;n<=days;n++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),e=state.expenses.some(x=>x.date===ds),inc=state.incomes.some(x=>x.date===ds),daily=w.some(x=>x.type==='daily'),hourly=w.some(x=>x.type==='hourly'),ot=w.some(x=>x.type==='overtime'),cls=daily?' daily':ot?' overtime':hourly?' hourly':e?' financeDay':inc?' incomeDay':' off',mark=daily?'▣':ot?'◷':hourly?'⌁':e?'●':inc?'＋':'';cells+=`<button class="day premiumDay${cls}${ds===iso()?' today':''}" onclick="openModal('day:${ds}')"><span class="dayNumber">${n}</span>${mark?`<span class="dayWorkIcon">${mark}</span>`:''}</button>`;}
 const prefix=`${y}-${String(m+1).padStart(2,'0')}`,mw=state.work.filter(x=>x.date?.startsWith(prefix)),me=state.expenses.filter(x=>x.date?.startsWith(prefix)),dn=mw.filter(x=>x.type==='daily').length,hn=mw.filter(x=>x.type==='hourly').length,on=mw.filter(x=>x.type==='overtime').length,road=me.filter(x=>x.workId||x.sourceType==='workRoad'||(x.category==='YOL'&&(x.title==='YOL'||String(x.note||'').includes('ÇALIŞMA YOL')))).reduce((a,x)=>a+(+x.amount||0),0),mn=d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'});
 return `${header('TAKVİM',true)}<div class="calendarBrandLine"><span class="calendarCrown">♛</span><div><b>RUTİN TAKVİM</b><small>PLANLA · KAYDET · BAŞAR</small></div></div><div class="calendarTitleRow premiumMonthRow"><button class="calendarArrow" onclick="moveCalendar(-1)">‹</button><div><b>${upper(mn)}</b><small>RENKLİ GÜNE DOKUN · DETAYI AÇ</small></div><button class="calendarArrow" onclick="moveCalendar(1)">›</button></div><div class="card compactCalendar referenceCalendar premiumCalendarCard"><div class="calendarHead">${['PZT','SAL','ÇAR','PER','CUM','CMT','PAZ'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar premiumCalendarGrid">${cells}</div><div class="calendarLegend premiumLegend"><span><i class="legendDaily"></i>TAM GÜN</span><span><i class="legendHourly"></i>SAATLİK</span><span><i class="legendOvertime"></i>MESAİ</span><span><i class="legendFinance"></i>HARCAMA</span></div></div><div class="section"><b>${upper(mn)} ÖZETİ</b><span>TOPLAM ${mw.length+me.length} KAYIT</span></div><div class="calendarSummaryGrid"><button onclick="go('daily')"><i class="sumIcon greenBox">▣</i><b>${dn}</b><small>TAM GÜN</small></button><button onclick="go('hourly')"><i class="sumIcon blueBox">◷</i><b>${hn}</b><small>SAATLİK</small></button><button onclick="go('overtime')"><i class="sumIcon goldBox">✦</i><b>${on}</b><small>MESAİ</small></button><button onclick="go('expenses')"><i class="sumIcon redBox">₺</i><b>${money(road)}</b><small>YOL</small></button></div><div class="calendarScenic"><div class="mountainLayer"></div><div class="scenicCopy"><b>Disiplin, hedeflerine giden yolu kısaltır.</b><small>Her renk, o gün yaptığın bir işi gösterir.</small></div></div>`;
};

function periodMovements(period){return [...filterByPeriod(state.incomes,period).map(x=>({...x,k:'income'})),...filterByPeriod(state.expenses,period).map(x=>({...x,k:'expense'})),...filterByPeriod(state.work,period).map(x=>({...x,k:'work'}))].sort((a,b)=>b.date.localeCompare(a.date))}
detailRows=function(period){const a=periodMovements(period);return a.length?a.map(x=>`<div class="movementRow item"><div class="ico">${x.k==='income'?'＋':x.k==='expense'?'−':'⌁'}</div><div><b>${esc(x.title||x.type)}</b><small>${x.date}${x.hours?` · ${x.hours} SAAT`:''}</small></div><div class="movementActions"><div class="amt ${x.k==='income'?'green':x.k==='expense'?'red':'gold'}">${x.k==='expense'?'-':x.k==='income'?'+':''}${money(x.k==='work'?workAmount(x):x.amount)}</div>${actionButtons(x.k,x.id,x.date)}</div></div>`).join(''):'<div class="notice">BU DÖNEMDE KAYIT YOK.</div>'};
function chartBreakdown(kind){const a=kind==='income'?filterByPeriod(state.incomes,reportPeriod):kind==='expense'?filterByPeriod(state.expenses,reportPeriod):filterByPeriod(state.work,reportPeriod);return `<div class="card list">${a.length?a.map(x=>`<div class="item"><div class="ico">${kind==='income'?'＋':kind==='expense'?'−':'⌁'}</div><div><b>${esc(x.title||x.type)}</b><small>${x.date}${x.category?' · '+x.category:''}</small></div><strong class="${kind==='expense'?'red':kind==='income'?'green':'gold'}">${money(kind==='work'?workAmount(x):x.amount)}</strong></div>`).join(''):'<div class="notice">KAYIT YOK.</div>'}</div>`}
reports=(function(old){return function(){return old().replace('onclick="go(\'detail\')">\n   <div class="donutCard">','onclick="openModal(\'chart:income\')">\n   <div class="donutCard">').replace('<div class="donutCard">\n     <div class="donutRing expenseRing"','<div class="donutCard" onclick="event.stopPropagation();openModal(\'chart:expense\')">\n     <div class="donutRing expenseRing"')}})(reports);
detailReport=(function(old){return function(){return old().replace('<div class="dualDonutWrap">','<div class="dualDonutWrap clickableChart" onclick="openModal(\'chart:income\')">').replace('<div class="chartBars">','<div class="chartBars clickableChart" onclick="openModal(\'chart:work\')">')}})(detailReport);

investments=function(){const a=state.investments.slice().sort((x,y)=>x.date.localeCompare(y.date)),max=Math.max(1,...a.map(x=>+x.amount||0));return `${header('YATIRIMLAR',true)}<div class="section"><b>TOPLAM DEĞER</b><span onclick="openModal('investment')">+ EKLE</span></div><div class="stat"><small>TOPLAM YATIRIM</small><strong class="green">${money(a.reduce((n,x)=>n+(+x.amount||0),0))}</strong></div><div class="section"><b>YATIRIM GRAFİĞİ</b><span>DEĞER DAĞILIMI</span></div><div class="card investmentChart">${a.length?a.map(x=>`<div class="investmentBarCol" onclick="openModal('editRecord:investment:${x.id}:${x.date}')"><div class="investmentBar" style="height:${Math.max(10,(+x.amount||0)/max*100)}%"></div><small>${esc(x.title).slice(0,8)}</small></div>`).join(''):'<div class="notice">GRAFİK İÇİN YATIRIM EKLE.</div>'}</div><div class="section"><b>YATIRIMLARIM</b></div><div class="card list">${a.length?a.slice().reverse().map(x=>`<div class="item"><div class="ico">↗</div><div><b>${esc(x.title)}</b><small>${x.date} · YATIRIM TÜRÜ</small></div><div class="investmentRight"><div class="amt green">${money(x.amount)}</div>${actionButtons('investment',x.id,x.date)}</div></div>`).join(''):'<div class="notice">HENÜZ YATIRIM KAYDI YOK.</div>'}</div>`};
submitEditInvestment=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const x=state.investments.find(z=>z.id===id);if(x)Object.assign(x,{title:upper(d.title||'YATIRIM'),amount:+d.amount||0,date:d.date});save();closeModal();render()};

finance=function(){return `${header('HESAPLARIM',true)}<div class="section"><b>KREDİ KARTLARIM</b><span onclick="openModal('addCard')">+ KART EKLE</span></div>${state.cards.length?state.cards.map(c=>`<div class="account premiumAccount goldBorder"><div class="accountHead"><b>${esc(c.name)}</b><button class="accountMenu" onclick="openModal('editCard:${c.id}')">⋯</button></div><strong>${money(c.balance)}</strong><small>LİMİT ${money(c.limit)}${c.statementDate?` · KESİM ${c.statementDate}`:''}${c.dueDate?` · SON ÖDEME ${c.dueDate}`:''}</small><button class="accountAction" onclick="openModal('cardSpend:${c.id}')">＋ KARTA HARCAMA EKLE</button><div class="miniTxnList">${(c.transactions||[]).slice(-3).reverse().map(t=>`<div><span>${esc(t.title)} · ${t.date}</span><b>${money(t.amount)}</b><button onclick="openModal('editCardSpend:${c.id}:${t.id}')">✎</button><button onclick="deleteCardSpend('${c.id}','${t.id}')">×</button></div>`).join('')}</div></div>`).join(''):'<div class="notice">HENÜZ KREDİ KARTI EKLENMEDİ.</div>'}<div class="section"><b>ESNEK HESAPLARIM</b><span onclick="openModal('addFlex')">+ HESAP EKLE</span></div>${state.flexAccounts.length?state.flexAccounts.map(c=>`<div class="account premiumAccount"><div class="accountHead"><b>${esc(c.name)}</b><button class="accountMenu" onclick="openModal('editFlex:${c.id}')">⋯</button></div><strong>${money(c.balance)}</strong><small>LİMİT ${money(c.limit)} · KULLANILABİLİR ${money(Math.max(0,c.limit-c.balance))}${c.statementDate?` · KESİM ${c.statementDate}`:''}${c.dueDate?` · SON ÖDEME ${c.dueDate}`:''}</small></div>`).join(''):'<div class="notice">HENÜZ ESNEK HESAP EKLENMEDİ.</div>'}<div class="section"><b>BAKİYE / NAKİT</b></div><div class="account cashAccount" onclick="openModal('cashCenter')"><div class="accountHead"><b>NAKİT PARA</b><span>›</span></div><strong>${money(state.accounts.cash.balance)}</strong><small>EKLE / ÇIKAR / HAREKETLERİ DÜZENLE</small></div><div class="account"><div class="accountHead"><b>YATIRIMLAR</b><span onclick="go('investments')">›</span></div><strong class="green">${money(state.investments.reduce((a,x)=>a+(+x.amount||0),0))}</strong></div>`};
submitCard=function(e,editId=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const prev=state.cards.find(z=>z.id===editId);const x={id:editId||uid(),name:upper(d.name||'KREDİ KARTI'),balance:+d.balance||0,limit:+d.limit||0,statementDate:d.statementDate||'',dueDate:d.dueDate||'',transactions:prev?.transactions||[]};if(editId){const i=state.cards.findIndex(z=>z.id===editId);state.cards[i]=x}else state.cards.push(x);save();closeModal();render()};
deleteCard=function(id){const c=state.cards.find(x=>x.id===id);if(c){const tids=new Set((c.transactions||[]).map(t=>t.id));state.expenses=state.expenses.filter(x=>!(x.sourceType==='card'&&x.cardId===id&&tids.has(x.sourceId)));}state.cards=state.cards.filter(x=>x.id!==id);save();closeModal();render()};
submitFlex=function(e,editId=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());const prev=state.flexAccounts.find(z=>z.id===editId);const x={id:editId||uid(),name:upper(d.name||'ESNEK HESAP'),balance:+d.balance||0,limit:+d.limit||0,statementDate:d.statementDate||'',dueDate:d.dueDate||'',transactions:prev?.transactions||[]};if(editId){const i=state.flexAccounts.findIndex(z=>z.id===editId);state.flexAccounts[i]=x}else state.flexAccounts.push(x);save();closeModal();render()};
submitCardSpend=function(e,cid,tid=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),c=state.cards.find(x=>x.id===cid);if(!c)return;let t=(c.transactions||[]).find(x=>x.id===tid);if(t){const diff=(+d.amount||0)-(+t.amount||0);Object.assign(t,{title:upper(d.title||'KART HARCAMASI'),amount:+d.amount||0,date:d.date});c.balance=(+c.balance||0)+diff;const ex=state.expenses.find(x=>x.sourceType==='card'&&x.sourceId===t.id);if(ex)Object.assign(ex,{title:t.title,amount:t.amount,date:t.date});}else{t={id:uid(),title:upper(d.title||'KART HARCAMASI'),amount:+d.amount||0,date:d.date};c.transactions.push(t);c.balance=(+c.balance||0)+t.amount;state.expenses.push({id:uid(),sourceType:'card',sourceId:t.id,cardId:cid,date:t.date,title:t.title,amount:t.amount,category:'DİĞER',method:c.name,note:'KART HARCAMASI'});}save();closeModal();render()};
deleteCardSpend=function(cid,tid){const c=state.cards.find(x=>x.id===cid);if(!c)return;const t=c.transactions.find(x=>x.id===tid);if(t)c.balance=Math.max(0,(+c.balance||0)-(+t.amount||0));c.transactions=c.transactions.filter(x=>x.id!==tid);state.expenses=state.expenses.filter(x=>!(x.sourceType==='card'&&x.sourceId===tid));save();render()};
function recalcCash(){state.accounts.cash.balance=state.cashTransactions.reduce((n,t)=>n+(t.type==='add'?1:-1)*(+t.amount||0),0)}
submitCashTxn=function(e,id=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());let t=state.cashTransactions.find(x=>x.id===id);if(t)Object.assign(t,{type:d.type,amount:+d.amount||0,title:upper(d.title||'NAKİT HAREKETİ'),date:d.date});else state.cashTransactions.push({id:uid(),type:d.type,amount:+d.amount||0,title:upper(d.title||'NAKİT HAREKETİ'),date:d.date});recalcCash();save();modal='cashCenter';render()};
deleteCashTxn=function(id){state.cashTransactions=state.cashTransactions.filter(x=>x.id!==id);recalcCash();save();modal='cashCenter';render()};

submitEditIncome=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),x=state.incomes.find(z=>z.id===id);if(x)Object.assign(x,{title:upper(d.title||'GELİR'),amount:+d.amount||0,date:d.date});save();closeModal();render()};
deleteRecord=function(kind,id,ds=''){if(kind==='work')return deleteWork(id,ds);if(kind==='expense'){const ex=state.expenses.find(x=>x.id===id);if(ex?.sourceType==='card'&&ex.cardId&&ex.sourceId){deleteCardSpend(ex.cardId,ex.sourceId);return;}state.expenses=state.expenses.filter(x=>x.id!==id);}if(kind==='income')state.incomes=state.incomes.filter(x=>x.id!==id);if(kind==='investment')state.investments=state.investments.filter(x=>x.id!==id);save();if(ds&&modal?.startsWith('day:'))modal=`day:${ds}`;else modal=null;render()};

const oldModalHtml=modalHtml;
modalHtml=function(k){let title='',body='';
 if(k.startsWith('day:')){const ds=k.split(':')[1];title=`${ds} · GÜN DETAYI`;body=dayModal(ds);}
 else if(k.startsWith('expenseDate:')){const ds=k.split(':')[1];title='HARCAMA EKLE';body=expenseFormFor(null).replace(`value="${iso()}"`,`value="${ds}"`);}
 else if(k.startsWith('editRecord:')){const p=k.split(':'),kind=p[1],id=p[2],ds=p[3]||'';if(kind==='work'){const x=state.work.find(z=>z.id===id);if(x){title='ÇALIŞMA KAYDINI DÜZENLE';body=`<form onsubmit="submitEditWork(event,'${x.id}','${ds}')">${field('date','TARİH',x.date,'date')}${field('title','İŞ / PROJE',esc(x.title))}${x.type==='daily'?field('amount','GÜNLÜK ÜCRET',x.amount||state.settings.dailyRate,'number'):`${field('hours',x.type==='hourly'?'ÇALIŞILAN SAAT':'MESAİ SAATİ',x.hours||0,'number')}${field('rate','SAATLİK ÜCRET',x.rate||(x.type==='hourly'?state.settings.hourlyRate:state.settings.overtimeRate),'number')}`}${x.type!=='overtime'?roadFields(x):''}<div class="field"><label>NOT</label><textarea name="note">${esc(x.note||'')}</textarea></div><button class="primary">DEĞİŞİKLİĞİ KAYDET</button></form>`;}}
 else if(kind==='expense'){const x=state.expenses.find(z=>z.id===id);title='HARCAMAYI DÜZENLE';body=x?expenseFormFor(x):'';}
 else if(kind==='income'){const x=state.incomes.find(z=>z.id===id);title='GELİRİ DÜZENLE';body=x?`<form onsubmit="submitEditIncome(event,'${x.id}')">${field('title','AÇIKLAMA',esc(x.title))}${field('amount','TUTAR',x.amount,'number')}${field('date','TARİH',x.date,'date')}<button class="primary">KAYDET</button></form>`:'';}
 else if(kind==='investment'){const x=state.investments.find(z=>z.id===id);title='YATIRIMI DÜZENLE';body=x?`<form onsubmit="submitEditInvestment(event,'${x.id}')">${field('title','YATIRIM NEDİR?',esc(x.title))}${field('amount','TUTAR',x.amount,'number')}${field('date','TARİH',x.date,'date')}<button class="primary">KAYDET</button><button type="button" class="secondary dangerBtn" onclick="deleteRecord('investment','${x.id}')">SİL</button></form>`:'';}}
 else if(k.startsWith('chart:')){const kind=k.split(':')[1];title=kind==='income'?'GELİR DÖKÜMÜ':kind==='expense'?'HARCAMA DÖKÜMÜ':'ÇALIŞMA DÖKÜMÜ';body=chartBreakdown(kind);}
 else if(k==='reminderCenter'){title='HATIRLATMALAR';const a=activeReminders();body=`<button class="premiumAddBtn full" onclick="openModal('addReminder')"><i>＋</i><span>MANUEL HATIRLATMA EKLE</span></button><div class="section"><b>AKTİF HATIRLATMALAR</b></div>${a.length?a.map(r=>`<div class="reminderCenterRow"><div><b>${esc(r.title)}</b><small>${esc(r.detail)}</small></div><button onclick="completeReminder('${r.id}','${r.rid||''}')">${r.kind==='payment'?'ÖDEDİM':'YAPTIM'}</button><button onclick="dismissReminder('${r.id}')">×</button></div>`).join(''):'<div class="notice">AKTİF HATIRLATMA YOK.</div>'}<div class="section"><b>MANUEL KAYITLAR</b></div>${state.manualReminders.map(r=>`<div class="reminderCenterRow ${r.done?'done':''}"><div><b>${esc(r.title)}</b><small>${r.date}${r.done?' · TAMAMLANDI':''}</small></div><button onclick="deleteManualReminder('${r.id}')">SİL</button></div>`).join('')}`;}
 else if(k==='addReminder'){title='MANUEL HATIRLATMA';body=`<form onsubmit="submitManualReminder(event)">${field('title','HATIRLATMA','')}${field('date','TARİH',iso(),'date')}<button class="primary">EKLE</button></form>`;}
 else if(k==='addCard'){title='KREDİ KARTI EKLE';body=`<form onsubmit="submitCard(event)">${field('name','KART ADI','ANA KART')}${field('balance','GÜNCEL BORÇ',0,'number')}${field('limit','LİMİT',0,'number')}${field('statementDate','HESAP KESİM TARİHİ','','date')}${field('dueDate','SON ÖDEME TARİHİ','','date')}<button class="primary">KARTI EKLE</button></form>`;}
 else if(k.startsWith('editCard:')){const c=state.cards.find(x=>x.id===k.split(':')[1]);title='KREDİ KARTI';body=c?`<form onsubmit="submitCard(event,'${c.id}')">${field('name','KART ADI',esc(c.name))}${field('balance','GÜNCEL BORÇ',c.balance,'number')}${field('limit','LİMİT',c.limit,'number')}${field('statementDate','HESAP KESİM TARİHİ',c.statementDate||'','date')}${field('dueDate','SON ÖDEME TARİHİ',c.dueDate||'','date')}<button class="primary">KAYDET</button><button type="button" class="secondary dangerBtn" onclick="deleteCard('${c.id}')">KARTI SİL</button></form>`:'';}
 else if(k==='addFlex'){title='ESNEK HESAP EKLE';body=`<form onsubmit="submitFlex(event)">${field('name','HESAP ADI','ESNEK HESAP')}${field('balance','KULLANILAN',0,'number')}${field('limit','LİMİT',0,'number')}${field('statementDate','HESAP KESİM TARİHİ','','date')}${field('dueDate','SON ÖDEME TARİHİ','','date')}<button class="primary">HESABI EKLE</button></form>`;}
 else if(k.startsWith('editFlex:')){const c=state.flexAccounts.find(x=>x.id===k.split(':')[1]);title='ESNEK HESAP';body=c?`<form onsubmit="submitFlex(event,'${c.id}')">${field('name','HESAP ADI',esc(c.name))}${field('balance','KULLANILAN',c.balance,'number')}${field('limit','LİMİT',c.limit,'number')}${field('statementDate','HESAP KESİM TARİHİ',c.statementDate||'','date')}${field('dueDate','SON ÖDEME TARİHİ',c.dueDate||'','date')}<button class="primary">KAYDET</button><button type="button" class="secondary dangerBtn" onclick="deleteFlex('${c.id}')">HESABI SİL</button></form>`:'';}
 else if(k.startsWith('cardSpend:')||k.startsWith('editCardSpend:')){const p=k.split(':'),cid=p[1],tid=p[2]||'',c=state.cards.find(x=>x.id===cid),t=c?.transactions?.find(x=>x.id===tid);title=t?'KART HARCAMASINI DÜZENLE':'KARTA HARCAMA EKLE';body=c?`<form onsubmit="submitCardSpend(event,'${cid}','${tid}')">${field('title','HARCAMA ADI',esc(t?.title||''))}${field('amount','TUTAR',t?.amount||0,'number')}${field('date','TARİH',t?.date||iso(),'date')}<button class="primary">KAYDET</button>${t?`<button type="button" class="secondary dangerBtn" onclick="deleteCardSpend('${cid}','${tid}');closeModal()">SİL</button>`:''}</form>`:'';}
 else if(k==='cashCenter'){title='NAKİT / BAKİYE';body=`<div class="cashBalanceHero"><small>MEVCUT NAKİT</small><strong>${money(state.accounts.cash.balance)}</strong></div><button class="premiumAddBtn full" onclick="openModal('cashTxn')"><i>＋</i><span>PARA EKLE / ÇIKAR</span></button><div class="section"><b>NAKİT HAREKETLERİ</b></div><div class="card list">${state.cashTransactions.slice().reverse().map(t=>`<div class="item"><div class="ico">${t.type==='add'?'＋':'−'}</div><div><b>${esc(t.title)}</b><small>${t.date}</small></div><div class="cashTxnRight"><b class="${t.type==='add'?'green':'red'}">${t.type==='add'?'+':'-'}${money(t.amount)}</b><button onclick="openModal('editCashTxn:${t.id}')">✎</button><button onclick="deleteCashTxn('${t.id}')">×</button></div></div>`).join('')||'<div class="notice">HENÜZ NAKİT HAREKETİ YOK.</div>'}</div>`;}
 else if(k==='cashTxn'||k.startsWith('editCashTxn:')){const id=k.split(':')[1]||'',t=state.cashTransactions.find(x=>x.id===id);title=t?'NAKİT HAREKETİNİ DÜZENLE':'NAKİT HAREKETİ';body=`<form onsubmit="submitCashTxn(event,'${id}')"><div class="field"><label>İŞLEM</label><select name="type"><option value="add" ${t?.type!=='remove'?'selected':''}>PARA EKLE</option><option value="remove" ${t?.type==='remove'?'selected':''}>PARA ÇIKAR</option></select></div>${field('title','AÇIKLAMA',esc(t?.title||'NAKİT'))}${field('amount','TUTAR',t?.amount||0,'number')}${field('date','TARİH',t?.date||iso(),'date')}<button class="primary">KAYDET</button></form>`;}
 else if(k==='investment'){title='YATIRIM EKLE';body=`<form onsubmit="submitInvestment(event)">${field('title','YATIRIM NEDİR?','')}${field('amount','TUTAR',0,'number')}${field('date','TARİH',iso(),'date')}<button class="primary">KAYDET</button></form>`;}
 else return oldModalHtml(k);
 return `<div class="modal" onclick="safeBackdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${title}</b><button class="close" type="button" onclick="event.preventDefault();event.stopPropagation();closeModal();return false">×</button></div>${body}</div></div>`;
};

nav=function(){const items=[['home','⌂','ANA SAYFA','navHome'],['work','▣','İŞ','navWork'],['expenses','₺','HARCAMA','navExpense'],['calendar','◫','TAKVİM','navCalendar'],['reports','▥','RAPOR','navReport'],['investments','◆','YATIRIM','navInvest'],['more','•••','DAHA FAZLA','navMore']];return `<div class="nav navSeven navV26">${items.map(x=>`<button class="${screen===x[0]?'active':''}" onclick="go('${x[0]}')"><i class="luxGlyph navLux ${x[3]}"><em>${x[1]}</em></i><span>${x[2]}</span></button>`).join('')}</div>`};
const oldRender=render;
render=function(){if(state.settings.lock&&!unlocked){$('#app').innerHTML=cleanPinScreen();requestAnimationFrame(()=>bindCleanPinControls());return;}let content='';if(screen==='expenses')content=expensesScreen();else{ // replicate original dispatch through temporarily mapped render-safe path
 if(screen==='home')content=home();else if(screen==='daily')content=workScreen('daily');else if(screen==='hourly')content=workScreen('hourly');else if(screen==='overtime')content=workScreen('overtime');else if(screen==='work')content=workScreen('daily');else if(screen==='finance')content=finance();else if(screen==='calendar')content=calendarScreen();else if(screen==='reports')content=reports();else if(screen==='detail')content=detailReport();else if(screen==='investments')content=investments();else if(screen==='notes')content=notes();else if(screen==='profile')content=profile();else if(screen==='settings')content=settings();else if(screen==='expense')content=expensesScreen();else if(screen==='more')content=`${header('DAHA FAZLA',true)}<div class="moreGrid"><button onclick="go('finance')"><i>▦</i><b>FİNANS / HESAPLAR</b><span>KARTLAR, ESNEK HESAP, NAKİT</span></button><button onclick="go('expenses')"><i>₺</i><b>HARCAMALAR</b><span>EKLE / DÜZENLE / SİL</span></button><button onclick="openModal('reminderCenter')"><i>◔</i><b>HATIRLATMALAR</b><span>MANUEL + OTOMATİK</span></button><button onclick="go('notes')"><i>✎</i><b>NOTLAR</b><span>KİŞİSEL VE İŞ NOTLARI</span></button><button onclick="go('profile')"><i>●</i><b>PROFİL</b><span>KİŞİSEL AYARLAR</span></button><button onclick="go('settings')"><i>⚙</i><b>AYARLAR</b><span>PIN, YEDEKLEME, TEMA</span></button></div>`;}
 $('#app').innerHTML=`<main class="phone">${content}${nav()}</main>${modal?modalHtml(modal):''}`;};

// Uygulamadan çıkar çıkmaz kilit hazırlanır; geri dönüldüğünde PIN ekranı açılır.
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&state.settings.lock){unlocked=false;modal=null;}else if(document.visibilityState==='visible'&&state.settings.lock&&!unlocked){render();}});
window.addEventListener('pagehide',()=>{if(state.settings.lock)unlocked=false;},{passive:true});
render();
})();
