(function(){
'use strict';
const E=v=>typeof esc==='function'?esc(String(v??'')):String(v??'');
const M=v=>typeof money==='function'?money(Number(v)||0):(Number(v)||0).toFixed(2)+' ₺';
const WA=x=>typeof workAmount==='function'?workAmount(x):(Number(x.amount)||((Number(x.hours)||0)*(Number(x.rate)||0))||0);
window.rutinReportCustom=window.rutinReportCustom||{start:'',end:''};
function today(){return typeof iso==='function'?iso(new Date()):new Date().toISOString().slice(0,10)}
function range(){
 const p=(typeof reportPeriod!=='undefined'?reportPeriod:'month');
 if(p==='custom'&&window.rutinReportCustom.start&&window.rutinReportCustom.end){let s=window.rutinReportCustom.start,e=window.rutinReportCustom.end;if(s>e)[s,e]=[e,s];return{start:s,end:e,label:'ÖZEL TARİH'};}
 const n=new Date(), y=n.getFullYear(), m=n.getMonth();
 if(p==='day'){const d=today();return{start:d,end:d,label:'BUGÜN'}}
 if(p==='week'){const d=new Date(n),q=(d.getDay()+6)%7,s=new Date(d);s.setDate(d.getDate()-q);const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e),label:'BU HAFTA'}}
 if(p==='year')return{start:y+'-01-01',end:y+'-12-31',label:String(y)};
 const last=new Date(y,m+1,0).getDate(),mm=String(m+1).padStart(2,'0');return{start:y+'-'+mm+'-01',end:y+'-'+mm+'-'+String(last).padStart(2,'0'),label:n.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).toUpperCase()};
}
function data(){const r=range(),inside=x=>x&&x.date>=r.start&&x.date<=r.end,w=(state.work||[]).filter(inside),i=(state.incomes||[]).filter(inside),e=(state.expenses||[]).filter(inside),d=w.filter(x=>x.type==='daily'),h=w.filter(x=>x.type==='hourly'),o=w.filter(x=>x.type==='overtime');return{r,w,i,e,d,h,o,dt:d.reduce((n,x)=>n+WA(x),0),ht:h.reduce((n,x)=>n+WA(x),0),ot:o.reduce((n,x)=>n+WA(x),0),it:i.reduce((n,x)=>n+(Number(x.amount)||0),0),et:e.reduce((n,x)=>n+(Number(x.amount)||0),0)}}
function row(kind,x){const amount=kind==='work'?WA(x):Number(x.amount)||0,label=kind==='work'?(x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ'):kind==='income'?(x.title||'DİĞER GELİR'):(x.category||'HARCAMA');return `<button class="globalRecordRowV435" onclick="openRecordV435('${kind}','${E(x.id)}')"><i>${kind==='expense'?'−':kind==='income'?'₺':'▣'}</i><div><b>${E(label)}</b><small>${E(x.date||'')}${x.hours?' · '+E(x.hours)+' SAAT':''}${kind==='expense'?' · '+E(x.method||'NAKİT'):''} · AYRINTI</small></div><strong class="${kind==='expense'?'red':kind==='income'?'green':'gold'}">${kind==='expense'?'-':'+'}${M(amount)}</strong><span>›</span></button>`}
function expenseGroups(a){const z={};a.forEach(x=>{const k=x.category||'DİĞER';(z[k]||(z[k]=[])).push(x)});return Object.entries(z).sort((a,b)=>b[1].reduce((n,x)=>n+(+x.amount||0),0)-a[1].reduce((n,x)=>n+(+x.amount||0),0));}
window.applyReportRangeV43101=function(){const s=document.getElementById('rrs43101')?.value,e=document.getElementById('rre43101')?.value;if(!s||!e){alert('BAŞLANGIÇ VE BİTİŞ TARİHİNİ SEÇ.');return}window.rutinReportCustom={start:s,end:e};reportPeriod='custom';closeModal();render();};
const oldModal=window.modalHtml;
window.modalHtml=function(k){if(k==='range'){const r=range();return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>TARİH ARALIĞI</b><button class="close" onclick="closeModal()">×</button></div><div class="rangeV439"><label>BAŞLANGIÇ<input id="rrs43101" type="date" value="${E(window.rutinReportCustom.start||r.start)}"></label><label>BİTİŞ<input id="rre43101" type="date" value="${E(window.rutinReportCustom.end||r.end)}"></label><button class="primary" onclick="applyReportRangeV43101()">RAPORU UYGULA</button></div></div></div>`}return oldModal(k)};
function tabs(){const p=reportPeriod,b=(k,l)=>`<button class="${p===k?'active':''}" onclick="reportPeriod='${k}';render()">${l}</button>`;return `<div class="tabs">${b('day','GÜNLÜK')}${b('week','HAFTALIK')}${b('month','AYLIK')}${b('year','YILLIK')}<button class="${p==='custom'?'active':''}" onclick="openModal('range')">ÖZEL TARİH</button></div>`}
window.openReportIncome43101=function(){openModal('reportIncome43101')};window.openReportExpense43101=function(){openModal('reportExpense43101')};
const modal2=window.modalHtml;window.modalHtml=function(k){if(k==='reportIncome43101'){const b=data(),all=[...b.w.map(x=>['work',x]),...b.i.map(x=>['income',x])].sort((a,c)=>(c[1].date||'').localeCompare(a[1].date||''));return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>GELİR DETAYI</b><button class="close" onclick="closeModal()">×</button></div><div class="reportBreakGridV439"><div><small>GÜNLÜK</small><b>${M(b.dt)}</b><em>${b.d.length} KAYIT</em></div><div><small>SAATLİK</small><b>${M(b.ht)}</b><em>${b.h.reduce((n,x)=>n+(+x.hours||0),0)} SAAT</em></div><div><small>MESAİ</small><b>${M(b.ot)}</b><em>${b.o.reduce((n,x)=>n+(+x.hours||0),0)} SAAT</em></div><div><small>DİĞER</small><b>${M(b.it)}</b><em>${b.i.length} KAYIT</em></div></div>${all.map(z=>row(z[0],z[1])).join('')||'<div class="notice">KAYIT YOK.</div>'}</div></div>`}if(k==='reportExpense43101'){const b=data(),g=expenseGroups(b.e);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>GİDER DETAYI</b><button class="close" onclick="closeModal()">×</button></div><div class="reportCatsV439">${g.map(([k,a])=>`<div><i>${window.rutinCategoryIcon?window.rutinCategoryIcon(k):'₺'}</i><span><small>${E(k)}</small><b>${M(a.reduce((n,x)=>n+(+x.amount||0),0))}</b></span><em>${a.length}</em></div>`).join('')||'<div class="notice">KAYIT YOK.</div>'}</div>${b.e.slice().sort((a,c)=>(c.date||'').localeCompare(a.date||'')).map(x=>row('expense',x)).join('')||'<div class="notice">KAYIT YOK.</div>'}</div></div>`}return modal2(k)};
window.reports=function(){const b=data(),income=b.dt+b.ht+b.ot+b.it,expense=b.et,net=income-expense,max=Math.max(1,income,expense),all=[...b.w.map(x=>['work',x]),...b.i.map(x=>['income',x])].sort((a,c)=>(c[1].date||'').localeCompare(a[1].date||''));return `${header('RAPORLAR',true)}${tabs()}<div class="section"><b>${E(b.r.label)}</b><span>${E(b.r.start)} / ${E(b.r.end)}</span></div><div class="reportGrid"><div class="reportBox"><small>TOPLAM GELİR</small><strong class="green">${M(income)}</strong></div><div class="reportBox"><small>TOPLAM HARCAMA</small><strong class="red">${M(expense)}</strong></div><div class="reportBox"><small>NET KAZANÇ</small><strong>${M(net)}</strong></div></div><div class="section"><b>GELİR / GİDER</b><span>GRAFİĞE DOKUN</span></div><div class="dualDonutWrap"><button class="donutCard reportChartBtnV439" onclick="openReportIncome43101()"><div class="donutRing incomeRing" style="--pct:${Math.round(income/max*100)}"><div class="donutCenter"><small>GELİR</small><strong class="green">${M(income)}</strong></div></div><div class="donutLegend"><i class="incomeDot"></i><span>GELİR DETAYI ›</span></div></button><button class="donutCard reportChartBtnV439" onclick="openReportExpense43101()"><div class="donutRing expenseRing" style="--pct:${Math.round(expense/max*100)}"><div class="donutCenter"><small>GİDER</small><strong class="red">${M(expense)}</strong></div></div><div class="donutLegend"><i class="expenseDot"></i><span>GİDER DETAYI ›</span></div></button></div><div class="section"><b>ÇALIŞMA ÖZETİ</b><span>AYRI HESAPLANIR</span></div><div class="summaryBox">${sumRow('GÜNLÜK ÇALIŞMA',b.d.length+' KAYIT · '+M(b.dt))}${sumRow('SAATLİK ÇALIŞMA',b.h.reduce((n,x)=>n+(+x.hours||0),0)+' SAAT · '+M(b.ht))}${sumRow('MESAİ',b.o.reduce((n,x)=>n+(+x.hours||0),0)+' SAAT · '+M(b.ot))}${sumRow('DİĞER GELİRLER',M(b.it))}</div><div class="section"><b>GELİR HAREKETLERİ</b><span>${all.length} KAYIT</span></div>${all.map(z=>row(z[0],z[1])).join('')||'<div class="notice">KAYIT YOK.</div>'}<div class="section"><b>GİDER HAREKETLERİ</b><span>${b.e.length} KAYIT</span></div>${b.e.slice().sort((a,c)=>(c.date||'').localeCompare(a.date||'')).map(x=>row('expense',x)).join('')||'<div class="notice">KAYIT YOK.</div>'}`};
window.detailReport=window.reports;
})();
