/* RUTIN V43.16.3 — REPORT COMPACT FIX + PERSONAL CARD FLOW (9-14) */
(function(){
const n=v=>Number(String(v??0).replace(',','.'))||0, E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ensure(){state.cards=Array.isArray(state.cards)?state.cards:[];state.cards.forEach(c=>{c.transactions=Array.isArray(c.transactions)?c.transactions:[];c.statementDay=c.statementDay||'';c.paymentDay=c.paymentDay||'';});}
ensure();
// Expense form: cash/card + exact card. Preserve flexible account option.
const oldExpenseForm=expenseForm;
expenseForm=function(){ensure();return `<form onsubmit="submitExpenseV43163(event)">
 ${field('amount','TUTAR',0,'number')}
 <div class="field"><label>KATEGORİ</label><div class="categoryIcons">${[['YOL','⌁'],['YEMEK','◉'],['MARKET','▣'],['FATURA','▤'],['KİRA','⌂'],['SAĞLIK','♡'],['ULAŞIM','◈'],['EĞLENCE','★'],['YAKIT','◒'],['GİYİM','♢'],['DİĞER','•••']].map(([c,i],x)=>`<label class="catChip"><input type="radio" name="category" value="${c}" ${x===0?'checked':''}><i>${i}</i><span>${c}</span></label>`).join('')}</div></div>
 <div class="field"><label>ÖDEME YÖNTEMİ</label><div class="payIcons"><label><input type="radio" name="method" value="NAKİT" checked onchange="toggleExpenseCardV43163(this.form)"><i>₺</i><span>NAKİT</span></label><label><input type="radio" name="method" value="KREDİ KARTI" onchange="toggleExpenseCardV43163(this.form)"><i>▣</i><span>KREDİ KARTI</span></label><label><input type="radio" name="method" value="ESNEK HESAP" onchange="toggleExpenseCardV43163(this.form)"><i>▥</i><span>ESNEK HESAP</span></label></div></div>
 <div class="field v43163CardPick" hidden><label>HANGİ KART?</label><select name="cardId"><option value="">KART SEÇ</option>${state.cards.map(c=>`<option value="${c.id}">${E(c.name)}</option>`).join('')}</select></div>
 ${field('date','TARİH',iso(),'date')}${textarea('note','NOT (İSTEĞE BAĞLI)')}<button class="primary">KAYDET</button></form>`};
window.toggleExpenseCardV43163=function(f){const el=f.querySelector('.v43163CardPick');if(el)el.hidden=f.method?.value!=='KREDİ KARTI'};
window.submitExpenseV43163=function(e){e.preventDefault();ensure();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),amount=n(d.amount);if(!amount)return alert('TUTAR GİRİN.');if(d.method==='KREDİ KARTI'&&!d.cardId)return alert('HANGİ KREDİ KARTINI KULLANDIĞINIZI SEÇİN.');const id=uid(),x={id,date:d.date||iso(),title:upper(d.category||'HARCAMA'),amount,category:d.category||'DİĞER',method:d.method||'NAKİT',cardId:d.cardId||'',note:d.note||''};state.expenses.push(x);if(x.method==='KREDİ KARTI'){const c=state.cards.find(z=>z.id===x.cardId);if(c){c.balance=n(c.balance)+amount;c.transactions.push({id:uid(),expenseId:id,title:x.title,category:x.category,amount,date:x.date,type:'spend'});}}save();modal=null;screen='finance';if(window.showToastV43162)showToastV43162('HARCAMA KAYDEDİLDİ ✓');render()};
// Card detail page + payment history.
window.openCardDetailV43163=function(id){window.cardDetailIdV43163=id;screen='cardDetailV43163';render()};
const oldRender=render;render=function(){if(screen==='cardDetailV43163'){document.getElementById('app').innerHTML=cardDetailV43163()+nav();return;}oldRender()};
window.cardDetailV43163=function(){ensure();const c=state.cards.find(x=>x.id===window.cardDetailIdV43163);if(!c){screen='finance';return finance()}const tx=[...c.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||''));const spends=tx.filter(x=>x.type==='spend').reduce((a,x)=>a+n(x.amount),0),pays=Math.abs(tx.filter(x=>x.type==='payment').reduce((a,x)=>a+n(x.amount),0));return `${header('KART EKSTRESİ',true)}<div class="cardDetailHeroV13"><small>${E(c.name)}</small><strong>${money(c.balance)}</strong><span>GÜNCEL BORÇ</span></div><div class="v43163CardStats"><div><small>DÖNEM HARCAMA</small><b>${money(spends)}</b></div><div><small>ÖDEMELER</small><b>${money(pays)}</b></div></div><div class="card v43163Dates"><span>HESAP KESİM <b>${E(c.statementDay||'-')}</b></span><span>SON ÖDEME <b>${E(c.paymentDay||c.dueDate||'-')}</b></span></div><button class="primary" onclick="openModal('cardPay4310:${c.id}')">NE KADAR ÖDEDİM?</button><div class="section"><b>EKSTRE HAREKETLERİ</b></div><div class="card list">${tx.length?tx.map(t=>`<div class="item"><div><b>${E(t.title||'HAREKET')}</b><small>${E(t.date||'')} · ${E(t.category|| (t.type==='payment'?'ÖDEME':''))}</small></div><strong class="${t.type==='payment'?'green':'red'}">${t.type==='payment'?'-':''}${money(Math.abs(n(t.amount)))}</strong></div>`).join(''):'<div class="notice">HENÜZ HAREKET YOK.</div>'}</div>`};
// Replace finance card tap with statement detail; keep menu on small action.
const oldFinance=finance;finance=function(){ensure();const html=oldFinance();return html.replace(/onclick="openCardMenuV4310\('([^']+)'\)"/g,`onclick="openCardDetailV43163('$1')"`)};
// Card add/edit: statement/payment dates. Use day-of-month to recur monthly.
const oldModal=modalHtml;modalHtml=function(k){ensure();if(k==='addCard'||k.startsWith('editCard:')){const id=k.split(':')[1]||'',c=state.cards.find(x=>x.id===id)||{};const title=id?'KREDİ KARTINI DÜZENLE':'KREDİ KARTI EKLE';const body=`<form onsubmit="submitCardV43163(event,'${id}')">${field('name','KART ADI',c.name||'')}${field('balance','GÜNCEL BORÇ',c.balance||0,'number')}${field('limit','LİMİT',c.limit||0,'number')}<div class="field"><label>HESAP KESİM GÜNÜ</label><input name="statementDay" type="number" min="1" max="31" value="${E(c.statementDay||'')}"></div><div class="field"><label>SON ÖDEME GÜNÜ</label><input name="paymentDay" type="number" min="1" max="31" value="${E(c.paymentDay||'')}"></div><button class="primary">KAYDET</button>${id?`<button type="button" class="secondary dangerBtn" onclick="deleteCard('${id}')">KARTI SİL</button>`:''}</form>`;return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${title}</b><button class="close" type="button" onclick="closeModal()">×</button></div>${body}</div></div>`;}return oldModal(k)};
window.submitCardV43163=function(e,id=''){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),c=id?state.cards.find(x=>x.id===id):null,x=c||{id:uid(),transactions:[]};x.name=upper(d.name||'KREDİ KARTI');x.balance=n(d.balance);x.limit=n(d.limit);x.statementDay=d.statementDay||'';x.paymentDay=d.paymentDay||'';if(!c)state.cards.push(x);save();closeModal();screen='finance';render()};
// Payment: preserve history + under/over warning before save.
window.submitCardPay4310=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),c=state.cards.find(x=>x.id===id);if(!c)return;const a=n(d.amount),due=n(c.balance),diff=a-due;let msg='';if(a<due)msg=`EKSİK ÖDEME: ${money(due-a)} BORÇ KALACAK.`;else if(a>due)msg=`FAZLA ÖDEME: ${money(diff)}.`;if(msg&&!confirm(msg+'\nDEVAM EDİLSİN Mİ?'))return;c.balance=Math.max(0,due-a);c.transactions=Array.isArray(c.transactions)?c.transactions:[];c.transactions.push({id:uid(),title:'KART ÖDEMESİ',amount:-a,date:d.date||iso(),type:'payment',dueBefore:due});save();closeModal();if(window.showToastV43162)showToastV43162('KART ÖDEMESİ KAYDEDİLDİ ✓');render()};
// Reports: only fix sizing/layout. Existing movement toggles remain untouched.
const oldReports=reports;reports=function(){let h=oldReports();h=h.replace('reportGrid v43162AccountingTop','v43163AccountingTop');return h};
save();
})();
