/* RUTIN V43.12.3 RECOVERY CENTER */
(function(){
const S=window.rutinSafety;if(!S)return;
function esc2(v){return window.esc?window.esc(v):String(v??'')}
function candidates(){const out=[];for(const k of ['rutin-main','rutin-v4','rutin-v3','rutin-v2','rutin-v1']){const s=S.readState(k);if(s)out.push({key:k,label:k==='rutin-main'?'MEVCUT VERİ':'ESKİ VERİ · '+k,state:s,counts:S.counts(s)})}S.snapshots().forEach((x,i)=>out.push({key:'snap:'+i,label:`GÜVENLİK KOPYASI · ${new Date(x.at).toLocaleString('tr-TR')}`,state:x.state,counts:x.counts||S.counts(x.state)}));return out}
function fpCard(c){return [String(c?.name||'').trim().toLocaleUpperCase('tr-TR'),Number(c?.balance)||0,Number(c?.limit)||0,String(c?.dueDate||''),JSON.stringify(c?.transactions||[])].join('|')}
window.rutinDeduplicateCardsSafe=function(){const seen=new Set(),next=[];for(const c of (state.cards||[])){const f=fpCard(c);if(seen.has(f))continue;seen.add(f);next.push(c)}const removed=(state.cards||[]).length-next.length;if(!removed){alert('AYNI BİLGİLERE SAHİP TEKRAR KART BULUNMADI.');return}if(!confirm(`${removed} ADET BİREBİR AYNI KART KAYDI BULUNDU. TEKRARLAR KALDIRILSIN MI?`))return;S.snapshot('KART TEMİZLEME ÖNCESİ',state);state.cards=next;save();alert('TEKRAR KARTLAR KALDIRILDI.');render()}
window.rutinRecoverInvestments=function(key){const c=candidates().find(x=>x.key===key);if(!c)return;const src=Array.isArray(c.state?.investments)?c.state.investments:[];if(!src.length){alert('BU KOPYADA YATIRIM KAYDI YOK.');return}const cur=Array.isArray(state.investments)?state.investments:[];const sig=x=>String(x?.id||[x?.name||x?.title,x?.date,x?.quantity,x?.unitPrice,x?.amount].join('|'));const seen=new Set(cur.map(sig)),add=src.filter(x=>!seen.has(sig(x)));if(!add.length){alert('BU KOPYADAKİ YATIRIMLAR ZATEN MEVCUT.');return}if(!confirm(`${add.length} YATIRIM KAYDI MEVCUT VERİLERE EKLENSİN Mİ?\nMEVCUT KAYITLAR SİLİNMEYECEK.`))return;S.snapshot('YATIRIM KURTARMA ÖNCESİ',state);state.investments=cur.concat(cloneSafe(add));save();alert(`${add.length} YATIRIM KAYDI KURTARILDI.`);render()}
function cloneSafe(x){return JSON.parse(JSON.stringify(x))}
window.rutinRestoreWhole=function(key){const c=candidates().find(x=>x.key===key);if(!c)return;if(!confirm('BU KOPYA TÜM MEVCUT RUTİN VERİLERİNİN YERİNE GERİ YÜKLENECEK. DEVAM EDİLSİN Mİ?'))return;S.snapshot('TAM GERİ YÜKLEME ÖNCESİ',state);state=cloneSafe(c.state);save();location.reload()}
window.rutinRecoveryBody=function(){const cs=candidates();return `<div class="notice">KURTARMA İŞLEMİNDEN ÖNCE MEVCUT VERİ OTOMATİK GÜVENLİK KOPYASINA ALINIR.</div><button class="primary" type="button" onclick="rutinDeduplicateCardsSafe()">AYNI KARTLARI GÜVENLİ TEMİZLE</button><div class="section"><b>BULUNAN VERİ KOPYALARI</b><span>${cs.length}</span></div><div class="card list">${cs.map(c=>`<div class="item" style="align-items:flex-start"><div class="ico">⇩</div><div style="min-width:0;flex:1"><b>${esc2(c.label)}</b><small>YATIRIM ${c.counts.investments} · KART ${c.counts.cards} · HARCAMA ${c.counts.expenses} · İŞ ${c.counts.work}</small><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px"><button class="secondary" type="button" onclick="rutinRecoverInvestments('${c.key}')">YATIRIMLARI KURTAR</button><button class="secondary" type="button" onclick="rutinRestoreWhole('${c.key}')">TÜMÜNÜ GERİ YÜKLE</button></div></div></div>`).join('')}</div>`}
// Snapshot post-load state too, without deleting any source.
S.snapshot('UYGULAMA AÇILIŞI',state);
const oldModal=modalHtml;modalHtml=function(k){if(k==='recovery43123')return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>VERİ KURTARMA MERKEZİ</b><button class="close" type="button" onclick="closeModal()">×</button></div>${rutinRecoveryBody()}</div></div>`;if(k==='backup'){return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>YEDEKLEME / GERİ YÜKLE</b><button class="close" type="button" onclick="closeModal()">×</button></div><button class="primary" onclick="downloadBackup()">YEDEK DOSYASI OLUŞTUR</button><button class="secondary" onclick="document.getElementById('restoreFile43123').click()">YEDEĞİ GERİ YÜKLE</button><input id="restoreFile43123" type="file" hidden onchange="restoreBackup(event)"><button class="secondary" onclick="openModal('recovery43123')">VERİ KURTARMA MERKEZİ</button><div class="notice">GÜNCELLEME ÖNCESİ KOPYALAR CİHAZDA SAKLANIR. GERİ YÜKLEMEDEN ÖNCE DE MEVCUT VERİ KORUNUR.</div></div></div>`}return oldModal(k)};
})();
