/* RUTIN V43.4 — Home income/expense interactive details */
(function(){
 const E=s=>typeof window.esc==='function'?window.esc(String(s??'')):String(s??'');
 const mp=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
 const workVal=x=>typeof window.workAmount==='function'?workAmount(x):(+x.amount||((+x.hours||0)*(+x.rate||0))||0);
 const inMonth=x=>String(x.date||'').startsWith(mp());
 const incomeParts=(today=false)=>{
  const f=x=>today?x.date===iso():inMonth(x);
  const w=state.work.filter(f), extra=state.incomes.filter(f);
  return {daily:w.filter(x=>x.type==='daily'),hourly:w.filter(x=>x.type==='hourly'),overtime:w.filter(x=>x.type==='overtime'),other:extra};
 };
 const sumWork=a=>a.reduce((n,x)=>n+workVal(x),0), sumAmt=a=>a.reduce((n,x)=>n+(+x.amount||0),0);
 function incomeRow(x,kind){const isWork=kind!=='other';return `<button class="homeDetailRow" onclick="openModal('editRecord:${isWork?'work':'income'}:${x.id}:${x.date||''}')"><div class="hdrIcon ${kind}">${kind==='daily'?'✓':kind==='hourly'?'◷':kind==='overtime'?'✦':'＋'}</div><div class="hdrText"><b>${E(x.title||({daily:'GÜNLÜK İŞ',hourly:'SAATLİK İŞ',overtime:'MESAİ',other:'DİĞER GELİR'}[kind]))}</b><small>${E(x.date||'')}${x.hours?' · '+E(x.hours)+' SAAT':''} · DOKUN VE DÜZENLE</small></div><strong class="green">${money(isWork?workVal(x):x.amount)}</strong></button>`}
 function incomeDetail(today){const p=incomeParts(today), groups=[['daily','GÜNLÜK İŞ',p.daily],['hourly','SAATLİK İŞ',p.hourly],['overtime','MESAİ',p.overtime],['other','DİĞER GELİRLER',p.other]], grand=groups.reduce((n,g)=>n+(g[0]==='other'?sumAmt(g[2]):sumWork(g[2])),0);return `<div class="homeAnalysisHero income"><small>${today?'BUGÜN':'BU AY'} TOPLAM GELİR</small><strong>${money(grand)}</strong><span>4 GELİR KAYNAĞI AYRI AYRI HESAPLANIR</span></div><div class="incomeSourceGrid">${groups.map(([k,t,a])=>`<button onclick="document.getElementById('inc-${k}').scrollIntoView({behavior:'smooth',block:'start'})"><i class="${k}">${k==='daily'?'✓':k==='hourly'?'◷':k==='overtime'?'✦':'＋'}</i><span>${t}</span><b>${money(k==='other'?sumAmt(a):sumWork(a))}</b><small>${a.length} KAYIT</small></button>`).join('')}</div>${groups.map(([k,t,a])=>`<div class="homeDetailSection" id="inc-${k}"><div class="section"><b>${t}</b><span>${a.length} KAYIT · ${money(k==='other'?sumAmt(a):sumWork(a))}</span></div>${a.length?a.slice().sort((x,y)=>(y.date||'').localeCompare(x.date||'')).map(x=>incomeRow(x,k)).join(''):'<div class="notice">KAYIT YOK.</div>'}</div>`).join('')}`}
 function expenseDetail(today){const items=state.expenses.filter(x=>today?x.date===iso():inMonth(x)).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')), map={};items.forEach(x=>{const c=String(x.category||'DİĞER').toUpperCase();(map[c]||(map[c]=[])).push(x)});const cats=Object.entries(map).sort((a,b)=>sumAmt(b[1])-sumAmt(a[1])),total=sumAmt(items);return `<div class="homeAnalysisHero expense"><small>${today?'BUGÜN':'BU AY'} TOPLAM HARCAMA</small><strong>${money(total)}</strong><span>${items.length} HAREKET · ${cats.length} KATEGORİ</span></div><div class="expenseCatDetailGrid">${cats.map(([c,a])=>`<button onclick="openModal('categoryDetail:${encodeURIComponent(c)}')"><i>${typeof ci==='function'?ci(c):'₺'}</i><span>${E(c)}</span><b>${money(sumAmt(a))}</b><small>${a.length} KAYIT</small></button>`).join('')||'<div class="notice">HARCAMA YOK.</div>'}</div><div class="section"><b>TÜM HARCAMA HAREKETLERİ</b><span>${items.length} KAYIT</span></div>${items.map(x=>`<button class="homeDetailRow" onclick="openModal('expenseDetailV4332:${x.id}')"><div class="hdrIcon expense">${typeof ci==='function'?ci(x.category||'DİĞER'):'₺'}</div><div class="hdrText"><b>${E(x.category==='DİĞER'?(x.customTitle||x.title||'DİĞER'):(x.title||x.category||'HARCAMA'))}${(x.recipient||x.person)?' · '+E(x.recipient||x.person):''}</b><small>${E(x.date||'')} · ${E(x.method||'NAKİT')} · DOKUN VE DÜZENLE/SİL</small></div><strong class="red">-${money(x.amount)}</strong></button>`).join('')||'<div class="notice">KAYIT YOK.</div>'}`}
 const oldModal=window.modalHtml;
 window.modalHtml=function(k){if(k==='homeIncomeMonth'||k==='homeIncomeToday'||k==='homeExpenseMonth'||k==='homeExpenseToday'){const inc=k.includes('Income'),today=k.includes('Today'),title=inc?'GELİR DETAYI':'HARCAMA DETAYI',body=inc?incomeDetail(today):expenseDetail(today);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet homeDetailSheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${title}</b><button class="close" type="button" onclick="closeModal()">×</button></div>${body}</div></div>`}return oldModal(k)};
 const oldHome=window.home;
 window.home=function(){let h=oldHome();h=h.replaceAll("periodDetail:todayIncome","homeIncomeToday").replaceAll("periodDetail:todayExpense","homeExpenseToday").replaceAll("periodDetail:monthIncome","homeIncomeMonth").replaceAll("periodDetail:monthExpense","homeExpenseMonth");return h};
})();
