(()=>{
const prevModal=window.modalHtml;
const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
function findRec(kind,id){const a=kind==='work'?state.work:kind==='expense'?state.expenses:state.incomes;return a.find(x=>String(x.id)===String(id));}
window.v4341Save=function(e,kind,id){e.preventDefault();const x=findRec(kind,id);if(!x)return;const d=Object.fromEntries(new FormData(e.currentTarget).entries());if(kind==='work'){x.date=d.date||x.date;x.title=(d.title||x.title||'ÇALIŞMA').toUpperCase();if(x.type==='daily')x.amount=+d.amount||0;else{x.hours=+d.hours||0;x.rate=+d.rate||0;x.amount=(+x.hours||0)*(+x.rate||0);}x.note=d.note||'';}else if(kind==='income'){x.title=(d.title||'GELİR').toUpperCase();x.amount=+d.amount||0;x.date=d.date||x.date;}else{x.title=(d.title||x.title||x.category||'HARCAMA').toUpperCase();x.amount=+d.amount||0;x.date=d.date||x.date;x.method=d.method||x.method||'NAKİT';x.note=d.note||'';if(d.recipient!==undefined)x.recipient=d.recipient||'';}save();modal=null;render();};
window.v4341Delete=function(kind,id){const x=findRec(kind,id);if(!x)return;if(!confirm('BU KAYIT SİLİNSİN Mİ?'))return;if(kind==='work')state.work=state.work.filter(z=>String(z.id)!==String(id));else if(kind==='income')state.incomes=state.incomes.filter(z=>String(z.id)!==String(id));else state.expenses=state.expenses.filter(z=>String(z.id)!==String(id));save();modal=null;render();};
function fld(n,l,v,t='text'){return `<div class="field"><label>${l}</label><input name="${n}" type="${t}" value="${E(v)}" required></div>`}
window.modalHtml=function(k){
 if(k.startsWith('editRecord:')){const p=k.split(':'),kind=p[1],id=p[2],x=findRec(kind,id);if(!x)return prevModal(k);let body='';
  if(kind==='work')body=`<form onsubmit="v4341Save(event,'work','${E(id)}')">${fld('date','TARİH',x.date,'date')}${fld('title','İŞ / PROJE',x.title)}${x.type==='daily'?fld('amount','GÜNLÜK ÜCRET',x.amount||0,'number'):fld('hours',x.type==='hourly'?'ÇALIŞILAN SAAT':'MESAİ SAATİ',x.hours||0,'number')+fld('rate','SAATLİK ÜCRET',x.rate||0,'number')}<div class="field"><label>NOT</label><textarea name="note">${E(x.note||'')}</textarea></div><button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('work','${E(id)}')">KAYDI SİL</button></form>`;
  else if(kind==='income')body=`<form onsubmit="v4341Save(event,'income','${E(id)}')">${fld('title','AÇIKLAMA',x.title)}${fld('amount','TUTAR',x.amount,'number')}${fld('date','TARİH',x.date,'date')}<button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('income','${E(id)}')">KAYDI SİL</button></form>`;
  else {const harclik=String(x.category||'').toUpperCase()==='HARÇLIK';body=`<form onsubmit="v4341Save(event,'expense','${E(id)}')">${fld('title','HARCAMA',x.title||x.category)}${fld('amount','TUTAR',x.amount,'number')}${fld('date','TARİH',x.date,'date')}<div class="field"><label>ÖDEME</label><select name="method"><option ${x.method==='NAKİT'?'selected':''}>NAKİT</option><option ${x.method==='KREDİ KARTI'?'selected':''}>KREDİ KARTI</option></select></div>${harclik?fld('recipient','KİME VERİLDİ?',x.recipient||x.person||''):''}<div class="field"><label>NOT</label><textarea name="note">${E(x.note||'')}</textarea></div><button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('expense','${E(id)}')">KAYDI SİL</button></form>`;}
  return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${kind==='work'?'ÇALIŞMA':kind==='income'?'GELİR':'HARCAMA'} KAYDINI DÜZENLE</b><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`;
 }
 return prevModal(k);
};
})();
