/* RUTIN V43.5 — application-wide record detail / edit / delete */
(function(){
 const E=s=>typeof window.esc==='function'?window.esc(String(s??'')):String(s??'');
 const W=x=>typeof window.workAmount==='function'?workAmount(x):(+x.amount||((+x.hours||0)*(+x.rate||0))||0);
 const arrFor=k=>k==='work'?state.work:k==='income'?state.incomes:state.expenses;
 const find=(k,id)=>arrFor(k).find(x=>String(x.id)===String(id));
 const typeName=x=>x.type==='daily'?'GÜNLÜK İŞ':x.type==='hourly'?'SAATLİK İŞ':x.type==='overtime'?'MESAİ':'ÇALIŞMA';
 const kindName=(k,x)=>k==='work'?typeName(x):k==='income'?'DİĞER GELİR':(typeof isWorkRoadExpense==='function'&&isWorkRoadExpense(x)?'YOL GİDERİ':'HARCAMA');
 const icon=(k,x)=>k==='work'?(x.type==='daily'?'✓':x.type==='hourly'?'◷':'✦'):k==='income'?'＋':(typeof ci==='function'?ci(x.category||'DİĞER'):'₺');
 const amount=(k,x)=>k==='work'?W(x):(+x.amount||0);
 window.openRecordV435=(k,id)=>openModal(`recordV435:${k}:${id}`);
 window.deleteRecordV435=function(k,id){const x=find(k,id);if(!x)return;if(!confirm('BU KAYIT SİLİNSİN Mİ?'))return;if(k==='work')state.work=state.work.filter(z=>String(z.id)!==String(id));else if(k==='income')state.incomes=state.incomes.filter(z=>String(z.id)!==String(id));else state.expenses=state.expenses.filter(z=>String(z.id)!==String(id));save();modal=null;render();};
 function row(k,x){const meta=[x.date,x.hours?`${x.hours} SAAT`:'',k==='work'?(x.paymentStatus==='paid'?'ÖDENDİ':'ÖDENMEDİ'):'',k==='expense'?(x.method||'NAKİT'):'',x.recipient||x.person||''].filter(Boolean).join(' · ');return `<button class="globalRecordRowV435" onclick="openRecordV435('${k}','${E(x.id)}')"><i>${icon(k,x)}</i><div><b>${E(x.title||x.category||kindName(k,x))}</b><small>${E(meta)} · AYRINTI / DÜZENLE / SİL</small></div><strong class="${k==='expense'?'red':k==='income'?'green':'gold'}">${k==='expense'?'-':'+'}${money(amount(k,x))}</strong><span>›</span></button>`}
 function detail(k,x){const road=k==='expense'&&typeof isWorkRoadExpense==='function'&&isWorkRoadExpense(x);return `<div class="recordHeroV435 ${k}"><i>${icon(k,x)}</i><div><small>${kindName(k,x)}</small><b>${E(x.title||x.category||kindName(k,x))}</b></div><strong>${k==='expense'?'-':'+'}${money(amount(k,x))}</strong></div><div class="recordInfoV435"><div><small>TARİH</small><b>${E(x.date||'-')}</b></div>${k==='work'&&x.hours?`<div><small>SAAT</small><b>${E(x.hours)} SAAT</b></div>`:''}${k==='work'&&x.rate?`<div><small>ÜCRET</small><b>${money(x.rate)} / SAAT</b></div>`:''}${k==='work'?`<div><small>ÖDEME DURUMU</small><b>${x.paymentStatus==='paid'?'ÖDENDİ':'ÖDENMEDİ'}</b></div>`:''}${k==='expense'?`<div><small>KATEGORİ</small><b>${E(x.category||'DİĞER')}</b></div><div><small>ÖDEME</small><b>${E(x.method||'NAKİT')}</b></div>`:''}${(x.recipient||x.person)?`<div><small>KİME VERİLDİ?</small><b>${E(x.recipient||x.person)}</b></div>`:''}${x.note?`<div class="wide"><small>NOT</small><b>${E(x.note)}</b></div>`:''}${road?`<div class="wide"><small>KAYIT TÜRÜ</small><b>ÇALIŞMA YOL GİDERİ</b></div>`:''}</div><div class="recordActionsV435"><button class="edit" onclick="openModal('editRecord:${k}:${E(x.id)}:${E(x.date||'')}')">✎ DÜZENLE</button><button class="delete" onclick="deleteRecordV435('${k}','${E(x.id)}')">× SİL</button></div>`}
 const oldModal=window.modalHtml;
 window.modalHtml=function(k){if(k.startsWith('recordV435:')){const p=k.split(':'),kind=p[1],id=p[2],x=find(kind,id);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet recordSheetV435" onclick="event.stopPropagation()"><div class="sheetHead"><b>KAYIT AYRINTISI</b><button class="close" onclick="closeModal()">×</button></div>${x?detail(kind,x):'<div class="notice">KAYIT BULUNAMADI.</div>'}</div></div>`}return oldModal(k)};
 function periodRows(){const p=window.reportPeriod||'month';return [...filterByPeriod(state.work,p).map(x=>({k:'work',x})),...filterByPeriod(state.incomes,p).map(x=>({k:'income',x})),...filterByPeriod(state.expenses,p).map(x=>({k:'expense',x}))].sort((a,b)=>String(b.x.date||'').localeCompare(String(a.x.date||'')));}
 window.detailRows=function(period){const a=[...filterByPeriod(state.incomes,period).map(x=>({k:'income',x})),...filterByPeriod(state.expenses,period).map(x=>({k:'expense',x})),...filterByPeriod(state.work,period).map(x=>({k:'work',x}))].sort((a,b)=>String(b.x.date||'').localeCompare(String(a.x.date||'')));return a.length?a.map(o=>row(o.k,o.x)).join(''):'<div class="notice">BU DÖNEMDE KAYIT YOK.</div>'};
 const oldReports=window.reports;
 window.reports=function(){let h=oldReports();const a=periodRows(),wi=a.filter(o=>o.k==='work'),ii=a.filter(o=>o.k==='income'),ee=a.filter(o=>o.k==='expense');const section=`<div class="section"><b>AYRINTILI HAREKETLER</b><span>${a.length} KAYIT</span></div><div class="reportMovementTabsV435"><button onclick="document.getElementById('v435-income').scrollIntoView({behavior:'smooth'})">GELİR <b>${wi.length+ii.length}</b></button><button onclick="document.getElementById('v435-expense').scrollIntoView({behavior:'smooth'})">GİDER <b>${ee.length}</b></button></div><div id="v435-income" class="reportGroupV435"><div class="section"><b>GELİR / ÇALIŞMA HAREKETLERİ</b><span>DOKUN → AYRINTI</span></div>${[...wi,...ii].map(o=>row(o.k,o.x)).join('')||'<div class="notice">KAYIT YOK.</div>'}</div><div id="v435-expense" class="reportGroupV435"><div class="section"><b>HARCAMA / YOL HAREKETLERİ</b><span>DOKUN → AYRINTI</span></div>${ee.map(o=>row(o.k,o.x)).join('')||'<div class="notice">KAYIT YOK.</div>'}</div>`;return h+section};
 const oldDetail=window.detailReport;
 window.detailReport=function(){return oldDetail()};
 // Convert home detail rows and expense detail entry points to the same global detail layer.
 const oldHomeModal=window.modalHtml;
 window.modalHtml=function(k){if(k.startsWith('expenseDetailV4332:')){const id=k.split(':')[1];return oldHomeModal(`recordV435:expense:${id}`)}return oldHomeModal(k)};
})();
