/* RUTIN V43.6 — Work premium + payment status + remembered inputs */
(function(){
 const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
 const lastDate=()=>state.settings.lastWorkDate||iso();
 const remembered=(k,fallback)=>{const v=state.settings[k];return (v!==undefined&&v!==null&&v!=='')?v:fallback};
 const payField=(v='unpaid')=>`<div class="field v436Pay"><label>ÖDEME DURUMU</label><div class="v436PayChoice"><label><input type="radio" name="paymentStatus" value="paid" ${v==='paid'?'checked':''}><span>✓ ÖDENDİ</span></label><label><input type="radio" name="paymentStatus" value="unpaid" ${v!=='paid'?'checked':''}><span>◷ ÖDENMEDİ</span></label></div></div>`;
 window.workPaymentLabel=x=>x&&x.paymentStatus==='paid'?'ÖDENDİ':'ÖDENMEDİ';
 window.dailyForm=function(){return `<form class="v436WorkForm" onsubmit="submitDaily(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastDailyTitle','ANA İŞ'))}${field('amount','GÜNLÜK ÜCRET',remembered('lastDailyRate',state.settings.dailyRate),'number')}${payField('unpaid')}<div class="field"><label>YOL PARASI</label><div class="choiceRow"><label><input type="radio" name="road" value="yes">ÖDEDİM</label><label><input type="radio" name="road" value="no" checked>ÖDEMEDİM</label></div></div>${field('roadAmount','YOL TUTARI (OPSİYONEL)',remembered('lastRoadAmount',0),'number')}${textarea('note','NOT')}<button class="primary">GÜNLÜK KAYDI EKLE</button></form>`};
 window.hourlyForm=function(){return `<form class="v436WorkForm" onsubmit="submitHourly(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastHourlyTitle','EK İŞ'))}${field('hours','ÇALIŞILAN SAAT',remembered('lastHourlyHours',0),'number')}${field('rate','SAATLİK ÜCRET',remembered('lastHourlyRate',state.settings.hourlyRate),'number')}${payField('unpaid')}<div class="field"><label>YOL PARASI</label><div class="choiceRow"><label><input type="radio" name="road" value="yes">ÖDEDİM</label><label><input type="radio" name="road" value="no" checked>ÖDEMEDİM</label></div></div>${field('roadAmount','YOL TUTARI (OPSİYONEL)',remembered('lastRoadAmount',0),'number')}${textarea('note','NOT')}<button class="primary">SAATLİK KAYDI EKLE</button></form>`};
 window.overtimeForm=function(){return `<form class="v436WorkForm" onsubmit="submitOvertime(event)">${field('date','TARİH',lastDate(),'date')}${field('title','İŞ / PROJE',remembered('lastOvertimeTitle','ANA İŞ'))}${field('hours','MESAİ SÜRESİ',remembered('lastOvertimeHours',0),'number')}${field('rate','MESAİ SAATLİK ÜCRET',remembered('lastOvertimeRate',state.settings.overtimeRate),'number')}${payField('unpaid')}${textarea('note','NOT')}<button class="primary">MESAİ KAYDI EKLE</button></form>`};
 function remember(d,type){state.settings.lastWorkDate=d.date||lastDate();if(type==='daily'){state.settings.lastDailyTitle=d.title||'ANA İŞ';state.settings.lastDailyRate=+d.amount||0}else if(type==='hourly'){state.settings.lastHourlyTitle=d.title||'EK İŞ';state.settings.lastHourlyHours=+d.hours||0;state.settings.lastHourlyRate=+d.rate||0}else{state.settings.lastOvertimeTitle=d.title||'ANA İŞ';state.settings.lastOvertimeHours=+d.hours||0;state.settings.lastOvertimeRate=+d.rate||0}if(d.roadAmount!==undefined)state.settings.lastRoadAmount=+d.roadAmount||0;}
 function addRoad(d){if(d.road==='yes'&&+d.roadAmount>0)state.expenses.push({id:uid(),date:d.date,title:'YOL',amount:+d.roadAmount,category:'YOL',method:'NAKİT',note:'ÇALIŞMA YOL MASRAFI'});}
 window.submitDaily=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'daily');state.work.push({id:uid(),type:'daily',date:d.date,title:upper(d.title||'ANA İŞ'),amount:+d.amount||0,paymentStatus:d.paymentStatus||'unpaid',note:d.note||''});addRoad(d);save();closeModal();render()};
 window.submitHourly=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'hourly');state.work.push({id:uid(),type:'hourly',date:d.date,title:upper(d.title||'EK İŞ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),paymentStatus:d.paymentStatus||'unpaid',note:d.note||''});addRoad(d);save();closeModal();render()};
 window.submitOvertime=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());remember(d,'overtime');state.work.push({id:uid(),type:'overtime',date:d.date,title:upper(d.title||'MESAİ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),paymentStatus:d.paymentStatus||'unpaid',note:d.note||''});save();closeModal();render()};
 window.workRows=function(type){const a=state.work.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);return a.length?a.map(x=>`<button class="v436WorkRow" onclick="openRecordV435('work','${E(x.id)}')"><div class="ico">${type==='daily'?'✓':type==='hourly'?'◷':'★'}</div><div class="v436WorkText"><b>${E(x.title)}</b><small>${E(x.date)}${x.hours?' · '+E(x.hours)+' SAAT':''}</small><em class="${x.paymentStatus==='paid'?'paid':'unpaid'}">${workPaymentLabel(x)}</em></div><strong>${money(x.amount||((x.hours||0)*(x.rate||0)))}</strong><span>›</span></button>`).join(''):'<div class="notice">HENÜZ KAYIT YOK.</div>'};
 // Existing records are safely treated as unpaid until explicitly marked paid.
 state.work.forEach(x=>{if(!x.paymentStatus)x.paymentStatus='unpaid'});
 const oldSave=window.v4341Save;
 window.v4341Save=function(e,kind,id){if(kind!=='work')return oldSave(e,kind,id);e.preventDefault();const x=state.work.find(z=>String(z.id)===String(id));if(!x)return;const d=Object.fromEntries(new FormData(e.currentTarget).entries());x.date=d.date||x.date;x.title=upper(d.title||x.title||'ÇALIŞMA');x.note=d.note||'';x.paymentStatus=d.paymentStatus||x.paymentStatus||'unpaid';if(x.type==='daily')x.amount=+d.amount||0;else{x.hours=+d.hours||0;x.rate=+d.rate||0;x.amount=x.hours*x.rate}remember(d,x.type);save();modal=null;render()};
 const prevModal=window.modalHtml;
 window.modalHtml=function(k){if(k.startsWith('editRecord:work:')){const p=k.split(':'),id=p[2],x=state.work.find(z=>String(z.id)===String(id));if(!x)return prevModal(k);const typeLabel=x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ';const fld=(n,l,v,t='text')=>`<div class="field"><label>${l}</label><input name="${n}" type="${t}" value="${E(v)}" required></div>`;const body=`<form class="v436WorkForm" onsubmit="v4341Save(event,'work','${E(id)}')">${fld('date','TARİH',x.date,'date')}${fld('title','İŞ / PROJE',x.title)}${x.type==='daily'?fld('amount','GÜNLÜK ÜCRET',x.amount||0,'number'):fld('hours',x.type==='hourly'?'ÇALIŞILAN SAAT':'MESAİ SAATİ',x.hours||0,'number')+fld('rate',x.type==='hourly'?'SAATLİK ÜCRET':'MESAİ SAATLİK ÜCRET',x.rate||0,'number')}${payField(x.paymentStatus||'unpaid')}<div class="field"><label>NOT</label><textarea name="note">${E(x.note||'')}</textarea></div><button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('work','${E(id)}')">KAYDI SİL</button></form>`;return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${typeLabel}</b><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`}return prevModal(k)};
})();
