/* RUTIN V43.7 — work income is earned immediately; multiple road expenses per work record */
(function(){
 const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
 const lastDate=()=>state.settings.lastWorkDate||iso();
 const remembered=(k,f)=>state.settings[k]!==undefined&&state.settings[k]!==''?state.settings[k]:f;
 const cards=()=>Array.isArray(state.cards)?state.cards:[];
 const methodOptions=(method='NAKİT',cardId='')=>`<select class="v437RoadMethod" onchange="v437ToggleCard(this)"><option value="NAKİT" ${method==='NAKİT'?'selected':''}>NAKİT</option><option value="KREDİ KARTI" ${String(method).includes('KREDİ')?'selected':''}>KREDİ KARTI</option></select><select class="v437RoadCard" ${String(method).includes('KREDİ')?'':'style="display:none"'}>${cards().map(c=>`<option value="${E(c.id)}" ${String(c.id)===String(cardId)?'selected':''}>${E(c.name||'KREDİ KARTI')}</option>`).join('')}</select>`;
 window.v437ToggleCard=function(sel){const card=sel.parentElement.querySelector('.v437RoadCard');if(card)card.style.display=sel.value==='KREDİ KARTI'?'':'none'};
 window.v437AddRoad=function(btn,road={}){const box=btn.closest('.v437RoadBox').querySelector('.v437RoadList');const row=document.createElement('div');row.className='v437RoadRow';row.innerHTML=`<select class="v437RoadDirection"><option value="GİDİŞ" ${road.direction==='GİDİŞ'?'selected':''}>GİDİŞ</option><option value="DÖNÜŞ" ${road.direction==='DÖNÜŞ'?'selected':''}>DÖNÜŞ</option><option value="YOL" ${!road.direction||road.direction==='YOL'?'selected':''}>YOL</option></select><input class="v437RoadAmount" type="number" inputmode="decimal" min="0" step="0.01" placeholder="TUTAR" value="${E(road.amount??state.settings.lastRoadAmount??'')}"><div class="v437RoadPay">${methodOptions(road.method||state.settings.lastRoadMethod||'NAKİT',road.cardId||state.settings.lastRoadCardId||'')}</div><button type="button" class="v437RoadRemove" onclick="this.closest('.v437RoadRow').remove()">×</button>`;box.appendChild(row)};
 function roadBox(existing=[]){return `<div class="v437RoadBox"><div class="v437RoadHead"><div><b>YOL GİDERLERİ</b><small>HER ARAÇ İÇİN AYRI ÖDEME EKLEYEBİLİRSİN</small></div></div><div class="v437RoadList"></div><button type="button" class="v437AddRoad" onclick="v437AddRoad(this)">＋ YOL EKLE</button><script type="application/json" class="v437Seed">${E(JSON.stringify(existing))}</script></div>`}
 function seedRoads(){document.querySelectorAll('.v437RoadBox').forEach(box=>{if(box.dataset.seeded)return;box.dataset.seeded='1';let a=[];try{a=JSON.parse(box.querySelector('.v437Seed')?.textContent||'[]')}catch(e){};const b=box.querySelector('.v437AddRoad');a.forEach(r=>v437AddRoad(b,r))})}
 const oldRender=window.render; window.render=function(){oldRender();setTimeout(seedRoads,0)};
 const oldOpen=window.openModal; window.openModal=function(k){oldOpen(k);setTimeout(seedRoads,0)};
 function form(type,x=null){const daily=type==='daily',hourly=type==='hourly',ot=type==='overtime';const roads=x?(state.expenses||[]).filter(r=>String(r.workId||'')===String(x.id)&&r.category==='YOL'):[];const date=x?.date||lastDate(), title=x?.title||remembered(daily?'lastDailyTitle':hourly?'lastHourlyTitle':'lastOvertimeTitle',daily||ot?'ANA İŞ':'EK İŞ');let fields=field('date','TARİH',date,'date')+field('title','İŞ / PROJE',title);if(daily)fields+=field('amount','GÜNLÜK ÜCRET',x?.amount??remembered('lastDailyRate',state.settings.dailyRate),'number');else fields+=field('hours',ot?'MESAİ SÜRESİ':'ÇALIŞILAN SAAT',x?.hours??remembered(ot?'lastOvertimeHours':'lastHourlyHours',0),'number')+field('rate',ot?'MESAİ SAATLİK ÜCRET':'SAATLİK ÜCRET',x?.rate??remembered(ot?'lastOvertimeRate':'lastHourlyRate',ot?state.settings.overtimeRate:state.settings.hourlyRate),'number');if(!ot)fields+=roadBox(roads);fields+=textarea('note','NOT',x?.note||'');return fields}
 window.dailyForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'daily')">${form('daily')}<button class="primary">GÜNLÜK KAYDI EKLE</button></form>`;
 window.hourlyForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'hourly')">${form('hourly')}<button class="primary">SAATLİK KAYDI EKLE</button></form>`;
 window.overtimeForm=()=>`<form class="v436WorkForm" onsubmit="v437SubmitWork(event,'overtime')">${form('overtime')}<button class="primary">MESAİ KAYDI EKLE</button></form>`;
 function remember(d,type){state.settings.lastWorkDate=d.date||lastDate();if(type==='daily'){state.settings.lastDailyTitle=d.title||'ANA İŞ';state.settings.lastDailyRate=+d.amount||0}else if(type==='hourly'){state.settings.lastHourlyTitle=d.title||'EK İŞ';state.settings.lastHourlyHours=+d.hours||0;state.settings.lastHourlyRate=+d.rate||0}else{state.settings.lastOvertimeTitle=d.title||'ANA İŞ';state.settings.lastOvertimeHours=+d.hours||0;state.settings.lastOvertimeRate=+d.rate||0}}
 function collectRoads(form,workId,date){return [...form.querySelectorAll('.v437RoadRow')].map(r=>{const amount=+r.querySelector('.v437RoadAmount').value||0, method=r.querySelector('.v437RoadMethod').value, direction=r.querySelector('.v437RoadDirection')?.value||'YOL', cardSel=r.querySelector('.v437RoadCard'), cardId=method==='KREDİ KARTI'?(cardSel?.value||''):'';const card=cards().find(c=>String(c.id)===String(cardId));if(amount>0){state.settings.lastRoadAmount=amount;state.settings.lastRoadMethod=method;state.settings.lastRoadCardId=cardId}return amount>0?{id:uid(),workId,date,title:'YOL',direction,amount,category:'YOL',method:method==='KREDİ KARTI'?'KREDİ KARTI':'NAKİT',cardId,cardName:card?.name||'',note:'ÇALIŞMA YOL GİDERİ'}:null}).filter(Boolean)}
 window.v437SubmitWork=function(e,type,id=''){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());let x=id?state.work.find(z=>String(z.id)===String(id)):null;if(!x){x={id:uid(),type};state.work.push(x)}x.type=type;x.date=d.date;x.title=upper(d.title||'ÇALIŞMA');x.note=d.note||'';delete x.paymentStatus;if(type==='daily')x.amount=+d.amount||0;else{x.hours=+d.hours||0;x.rate=+d.rate||0;x.amount=x.hours*x.rate}remember(d,type);state.expenses=(state.expenses||[]).filter(r=>String(r.workId||'')!==String(x.id));if(type!=='overtime')state.expenses.push(...collectRoads(f,x.id,x.date));save();modal=null;render()};
 window.workRows=function(type){const a=state.work.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);return a.length?a.map(x=>{const rc=(state.expenses||[]).filter(r=>String(r.workId||'')===String(x.id)&&r.category==='YOL'),rt=rc.reduce((n,r)=>n+(+r.amount||0),0);return `<button class="v436WorkRow" onclick="openRecordV435('work','${E(x.id)}')"><div class="ico">${type==='daily'?'✓':type==='hourly'?'◷':'★'}</div><div class="v436WorkText"><b>${E(x.title)}</b><small>${E(x.date)}${x.hours?' · '+E(x.hours)+' SAAT':''}${rt?' · YOL '+money(rt):''}</small><em class="paid">KAZANÇ HESABA DAHİL</em></div><strong>${money(x.amount||0)}</strong><span>›</span></button>`}).join(''):'<div class="notice">HENÜZ KAYIT YOK.</div>'};
 const prevModal=window.modalHtml; window.modalHtml=function(k){if(k.startsWith('editRecord:work:')){const id=k.split(':')[2],x=state.work.find(z=>String(z.id)===String(id));if(!x)return prevModal(k);const label=x.type==='daily'?'GÜNLÜK ÇALIŞMA':x.type==='hourly'?'SAATLİK ÇALIŞMA':'MESAİ';return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>${label}</b><button class="close" onclick="closeModal()">×</button></div><form class="v436WorkForm" onsubmit="v437SubmitWork(event,'${x.type}','${E(id)}')">${form(x.type,x)}<button class="primary">DEĞİŞİKLİĞİ KAYDET</button><button type="button" class="v4341Delete" onclick="v4341Delete('work','${E(id)}')">KAYDI SİL</button></form></div></div>`}return prevModal(k)};
 state.work.forEach(x=>{if(x.paymentStatus)delete x.paymentStatus}); save();
})();
