/* RUTIN V43.8 — grouped daily road movement + individual road edit/delete */
(function(){
 const E=s=>window.esc?window.esc(String(s??'')):String(s??'');
 const roads=()=> (state.expenses||[]).filter(x=>String(x.category||'').toUpperCase()==='YOL' && x.workId);
 const sum=a=>a.reduce((n,x)=>n+(+x.amount||0),0);
 const groupKey=x=>`${x.date||''}__${x.workId||''}`;
 const groupFor=(date,workId)=>roads().filter(x=>String(x.date||'')===String(date||'')&&String(x.workId||'')===String(workId||''));
 const payTotals=a=>({cash:sum(a.filter(x=>String(x.method||'').toUpperCase().includes('NAKİT'))),card:sum(a.filter(x=>String(x.method||'').toUpperCase().includes('KREDİ')))});
 window.openRoadGroupV438=(date,workId)=>openModal(`roadGroupV438:${date}:${workId}`);
 window.deleteRoadV438=function(id,date,workId){if(!confirm('BU YOL ÖDEMESİ SİLİNSİN Mİ?'))return;state.expenses=(state.expenses||[]).filter(x=>String(x.id)!==String(id));save();openRoadGroupV438(date,workId);render()};
 function roadGroupCard(date,workId,a){const p=payTotals(a);return `<button class="roadGroupCardV438" onclick="openRoadGroupV438('${E(date)}','${E(workId)}')"><div class="roadGroupIconV438">🚗</div><div><b>YOL GİDERİ</b><small>${E(date)} · ${a.length} ÖDEME</small><em>${p.card?money(p.card)+' KART':''}${p.card&&p.cash?' · ':''}${p.cash?money(p.cash)+' NAKİT':''}</em></div><strong>-${money(sum(a))}</strong><span>›</span></button>`}
 function groupRoadItems(items){const normal=items.filter(x=>!(String(x.category||'').toUpperCase()==='YOL'&&x.workId));const gm={};items.filter(x=>String(x.category||'').toUpperCase()==='YOL'&&x.workId).forEach(x=>(gm[groupKey(x)]||(gm[groupKey(x)]=[])).push(x));return {normal,groups:Object.values(gm).sort((a,b)=>(b[0]?.date||'').localeCompare(a[0]?.date||''))}}
 window.roadGroupCardV438=roadGroupCard; window.groupRoadItemsV438=groupRoadItems;
 const prevModal=window.modalHtml; window.modalHtml=function(k){
   if(k.startsWith('roadGroupV438:')){const p=k.split(':'),date=p[1],workId=p.slice(2).join(':'),a=groupFor(date,workId),pt=payTotals(a);return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet v438RoadSheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>YOL GİDERİ DETAYI</b><button class="close" onclick="closeModal()">×</button></div><div class="roadHeroV438"><small>${E(date)} · ${a.length} ÖDEME</small><strong>${money(sum(a))}</strong><div><span>💳 ${money(pt.card)} KART</span><span>💵 ${money(pt.cash)} NAKİT</span></div></div><div class="section"><b>YOL ÖDEMELERİ</b><span>TEK TEK DÜZENLE / SİL</span></div>${a.map((x,i)=>`<div class="roadItemV438"><button class="roadItemMainV438" onclick="openRecordV435('expense','${E(x.id)}')"><i>${E(x.direction||((i%2)?'DÖNÜŞ':'GİDİŞ'))}</i><div><b>${E(x.direction||'YOL')} · ${money(x.amount)}</b><small>${E(x.method||'NAKİT')}${x.cardName?' · '+E(x.cardName):''}</small></div><span>›</span></button><button class="roadItemDeleteV438" onclick="deleteRoadV438('${E(x.id)}','${E(date)}','${E(workId)}')">SİL</button></div>`).join('')||'<div class="notice">YOL ÖDEMESİ YOK.</div>'}</div></div>`}
   return prevModal(k)
 };
 // Reports: replace only the appended detailed movement area with grouped road display.
 const oldReports=window.reports; window.reports=function(){let h=oldReports();try{const marker='<div class="section"><b>AYRINTILI HAREKETLER</b>';const at=h.lastIndexOf(marker);if(at>=0){const base=h.slice(0,at);const s=state.reportStart||monthStart(),e=state.reportEnd||monthEnd();const inP=d=>d>=s&&d<=e;const work=(state.work||[]).filter(x=>inP(x.date)).sort((a,b)=>b.date.localeCompare(a.date));const inc=(state.incomes||[]).filter(x=>inP(x.date)).sort((a,b)=>b.date.localeCompare(a.date));const exp=(state.expenses||[]).filter(x=>inP(x.date));const g=groupRoadItems(exp), normal=g.normal.sort((a,b)=>(b.date||'').localeCompare(a.date||''));const wr=work.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('work','${E(x.id)}')"><i>▣</i><div><b>${E(x.title||'ÇALIŞMA')}</b><small>${E(x.date)} · AYRINTI / DÜZENLE / SİL</small></div><strong class="gold">+${money(x.amount||0)}</strong><span>›</span></button>`).join('');const ir=inc.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('income','${E(x.id)}')"><i>₺</i><div><b>${E(x.title||'DİĞER GELİR')}</b><small>${E(x.date)} · AYRINTI / DÜZENLE / SİL</small></div><strong class="green">+${money(x.amount||0)}</strong><span>›</span></button>`).join('');const er=normal.map(x=>`<button class="globalRecordRowV435" onclick="openRecordV435('expense','${E(x.id)}')"><i>${window.rutinCategoryIcon?window.rutinCategoryIcon(x.category||'DİĞER'):'₺'}</i><div><b>${E(x.category||x.title||'HARCAMA')}</b><small>${E(x.date)} · ${E(x.method||'NAKİT')} · AYRINTI / DÜZENLE / SİL</small></div><strong class="red">-${money(x.amount||0)}</strong><span>›</span></button>`).join('');const rg=g.groups.map(a=>roadGroupCard(a[0].date,a[0].workId,a)).join('');return base+`<div class="section"><b>AYRINTILI HAREKETLER</b><span>GRUPLU YOL</span></div><div class="reportGroupV435"><div class="section"><b>GELİR / ÇALIŞMA HAREKETLERİ</b><span>DOKUN → AYRINTI</span></div>${wr+ir||'<div class="notice">KAYIT YOK.</div>'}</div><div class="reportGroupV435"><div class="section"><b>HARCAMA / YOL HAREKETLERİ</b><span>YOL GÜN BAZINDA TEK KART</span></div>${rg+er||'<div class="notice">KAYIT YOK.</div>'}</div>`;}
   }catch(e){}return h};
 // Calendar day menu: collapse road rows into one daily card, while preserving other records.
 const oldCalendarScreen=window.calendarScreen; if(oldCalendarScreen){ /* display layer is handled by CSS/modal grouping where possible */ }
})();
