(function(){
'use strict';
const E=s=>typeof esc==='function'?esc(String(s??'')):String(s??'');
const W=x=>typeof workAmount==='function'?workAmount(x):(+x.amount||((+x.hours||0)*(+x.rate||0))||0);
const M=n=>typeof money==='function'?money(+n||0):(+n||0).toFixed(2)+' ₺';
window.reportStart=window.reportStart||''; window.reportEnd=window.reportEnd||'';
const oldRange=window.dateRangeForPeriod;
window.dateRangeForPeriod=function(p=window.reportPeriod||reportPeriod){
 if(p==='custom' && window.reportStart && window.reportEnd){let s=window.reportStart,e=window.reportEnd;if(s>e){const t=s;s=e;e=t}return {start:s,end:e,label:`${s} — ${e}`};}
 return oldRange(p);
};
window.applyReportRangeV439=function(){const s=document.getElementById('reportStartV439')?.value,e=document.getElementById('reportEndV439')?.value;if(!s||!e)return alert('BAŞLANGIÇ VE BİTİŞ TARİHİNİ SEÇ.');window.reportStart=s;window.reportEnd=e;window.reportPeriod='custom';try{reportPeriod='custom'}catch(_){} closeModal();render();};
function rangeItems(a){const r=dateRangeForPeriod(window.reportPeriod||reportPeriod);return (a||[]).filter(x=>x.date>=r.start&&x.date<=r.end)}
function breakdown(){const work=rangeItems(state.work),inc=rangeItems(state.incomes),exp=rangeItems(state.expenses);const daily=work.filter(x=>x.type==='daily'),hourly=work.filter(x=>x.type==='hourly'),ot=work.filter(x=>x.type==='overtime');return {work,inc,exp,daily,hourly,ot,dailyT:daily.reduce((n,x)=>n+W(x),0),hourlyT:hourly.reduce((n,x)=>n+W(x),0),otT:ot.reduce((n,x)=>n+W(x),0),otherT:inc.reduce((n,x)=>n+(+x.amount||0),0)};}
function catGroups(exp){const m={};exp.forEach(x=>{const k=x.category||'DİĞER';(m[k]||(m[k]=[])).push(x)});return Object.entries(m).sort((a,b)=>b[1].reduce((n,x)=>n+(+x.amount||0),0)-a[1].reduce((n,x)=>n+(+x.amount||0),0));}
function rec(kind,x){const val=kind==='work'?W(x):(+x.amount||0),lab=kind==='work'?(x.type==='daily'?'GÜNLÜK İŞ':x.type==='hourly'?'SAATLİK İŞ':'MESAİ'):(kind==='income'?'DİĞER GELİR':(x.category||'HARCAMA'));return `<button class="reportRecV439" onclick="openRecordV435('${kind}','${E(x.id)}')"><i>${kind==='expense'?'−':kind==='income'?'+':'✓'}</i><div><b>${E(lab)}</b><small>${E(x.date)}${x.hours?' · '+E(x.hours)+' SAAT':''}${kind==='expense'?' · '+E(x.method||'NAKİT'):''}</small></div><strong class="${kind==='expense'?'red':kind==='income'?'green':'gold'}">${kind==='expense'?'-':'+'}${M(val)}</strong><span>›</span></button>`}
window.reportIncomeDetailV439=function(){const b=breakdown();return `<div class="reportBreakGridV439"><div><small>GÜNLÜK İŞ</small><b>${M(b.dailyT)}</b><em>${b.daily.length} KAYIT</em></div><div><small>SAATLİK İŞ</small><b>${M(b.hourlyT)}</b><em>${b.hourly.reduce((n,x)=>n+(+x.hours||0),0)} SAAT</em></div><div><small>MESAİ</small><b>${M(b.otT)}</b><em>${b.ot.reduce((n,x)=>n+(+x.hours||0),0)} SAAT</em></div><div><small>DİĞER GELİR</small><b>${M(b.otherT)}</b><em>${b.inc.length} KAYIT</em></div></div><div class="section"><b>GELİR HAREKETLERİ</b><span>DOKUN → DÜZENLE / SİL</span></div>${[...b.work.map(x=>['work',x]),...b.inc.map(x=>['income',x])].sort((a,c)=>c[1].date.localeCompare(a[1].date)).map(z=>rec(z[0],z[1])).join('')||'<div class="notice">KAYIT YOK.</div>'}`};
window.reportExpenseDetailV439=function(){const b=breakdown(),groups=catGroups(b.exp);return `<div class="reportCatsV439">${groups.map(([k,a])=>`<div><i>${typeof ci==='function'?ci(k):'₺'}</i><span><small>${E(k)}</small><b>${M(a.reduce((n,x)=>n+(+x.amount||0),0))}</b></span><em>${a.length}</em></div>`).join('')||'<div class="notice">KAYIT YOK.</div>'}</div><div class="section"><b>GİDER HAREKETLERİ</b><span>DOKUN → DÜZENLE / SİL</span></div>${b.exp.sort((a,c)=>c.date.localeCompare(a.date)).map(x=>rec('expense',x)).join('')||'<div class="notice">KAYIT YOK.</div>'}`};
const oldModal=window.modalHtml;
window.modalHtml=function(k){if(k==='range'){const now=new Date(),defS=window.reportStart||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`,defE=window.reportEnd||iso();return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>TARİH ARALIĞI</b><button class="close" onclick="closeModal()">×</button></div><div class="rangeV439"><label>BAŞLANGIÇ<input id="reportStartV439" type="date" value="${defS}"></label><label>BİTİŞ<input id="reportEndV439" type="date" value="${defE}"></label><button class="primary" onclick="applyReportRangeV439()">RAPORU UYGULA</button></div></div></div>`}if(k==='reportIncomeV439')return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>GELİR DETAYI</b><button class="close" onclick="closeModal()">×</button></div>${reportIncomeDetailV439()}</div></div>`;if(k==='reportExpenseV439')return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>GİDER DETAYI</b><button class="close" onclick="closeModal()">×</button></div>${reportExpenseDetailV439()}</div></div>`;return oldModal(k)};
function tabs(){const p=window.reportPeriod||reportPeriod;const b=(k,l)=>`<button class="${p===k?'active':''}" onclick="window.reportPeriod='${k}';reportPeriod='${k}';render()">${l}</button>`;return `<div class="tabs">${b('day','GÜNLÜK')}${b('month','AYLIK')}${b('year','YILLIK')}<button class="${p==='custom'?'active':''}" onclick="openModal('range')">ÖZEL TARİH</button></div>`}
window.reports=function(){const b=breakdown(),r=dateRangeForPeriod(window.reportPeriod||reportPeriod),income=b.dailyT+b.hourlyT+b.otT+b.otherT,expense=b.exp.reduce((n,x)=>n+(+x.amount||0),0),net=income-exp,max=Math.max(1,income,expense);return `${header('RAPORLAR',true)}${tabs()}<div class="section"><b>${E(r.label)}</b><span>${r.start} / ${r.end}</span></div><div class="reportGrid"><div class="reportBox"><small>TOPLAM GELİR</small><strong class="green">${M(income)}</strong></div><div class="reportBox"><small>TOPLAM HARCAMA</small><strong class="red">${M(expense)}</strong></div><div class="reportBox"><small>NET KAZANÇ</small><strong>${M(net)}</strong></div></div><div class="section"><b>GELİR / GİDER GRAFİKLERİ</b><span>DOKUN → DETAY</span></div><div class="dualDonutWrap"><button class="donutCard reportChartBtnV439" onclick="openModal('reportIncomeV439')"><div class="donutRing incomeRing" style="--pct:${Math.round(income/max*100)}"><div class="donutCenter"><small>GELİR</small><strong class="green">${M(income)}</strong></div></div><div class="donutLegend"><i class="incomeDot"></i><span>GELİR DETAYI ›</span></div></button><button class="donutCard reportChartBtnV439" onclick="openModal('reportExpenseV439')"><div class="donutRing expenseRing" style="--pct:${Math.round(expense/max*100)}"><div class="donutCenter"><small>GİDER</small><strong class="red">${M(expense)}</strong></div></div><div class="donutLegend"><i class="expenseDot"></i><span>GİDER DETAYI ›</span></div></button></div><div class="section"><b>ÇALIŞMA ÖZETİ</b><span>AYRI HESAPLANIR</span></div><div class="summaryBox">${sumRow('GÜNLÜK ÇALIŞMA',b.daily.length+' KAYIT · '+M(b.dailyT))}${sumRow('SAATLİK ÇALIŞMA',b.hourly.reduce((n,x)=>n+(+x.hours||0),0)+' SAAT · '+M(b.hourlyT))}${sumRow('MESAİ',b.ot.reduce((n,x)=>n+(+x.hours||0),0)+' SAAT · '+M(b.otT))}${sumRow('DİĞER GELİRLER',M(b.otherT))}</div><div class="section"><b>GELİR HAREKETLERİ</b><span>${b.work.length+b.inc.length} KAYIT</span></div>${[...b.work.map(x=>['work',x]),...b.inc.map(x=>['income',x])].sort((a,c)=>c[1].date.localeCompare(a[1].date)).map(z=>rec(z[0],z[1])).join('')||'<div class="notice">KAYIT YOK.</div>'}<div class="section"><b>GİDER HAREKETLERİ</b><span>${b.exp.length} KAYIT</span></div>${b.exp.sort((a,c)=>c.date.localeCompare(a.date)).map(x=>rec('expense',x)).join('')||'<div class="notice">KAYIT YOK.</div>'}`};
window.detailReport=window.reports;
})();
