(()=>{
const V='v45';
state.ui=state.ui||{}; state.ui.financeTab=state.ui.financeTab||'cards'; state.ui.reportFrom=state.ui.reportFrom||''; state.ui.reportTo=state.ui.reportTo||'';
state.lastEntry=state.lastEntry||{date:iso(),dailyAmount:state.settings.dailyRate||0,hourlyRate:state.settings.hourlyRate||0,overtimeRate:state.settings.overtimeRate||0,roadAmount:0};
const oldModalV43=modalHtml;
const U=s=>String(s??'').toLocaleUpperCase('tr-TR');
const catTotals=(arr)=>Object.entries(arr.reduce((o,x)=>{const k=U(x.category||x.title||'DİĞER');o[k]=(o[k]||0)+(+x.amount||0);return o},{})).sort((a,b)=>b[1]-a[1]);
const workIncome=x=>typeof workAmount==='function'?workAmount(x):(+x.amount||((+x.hours||0)*(+x.rate||0)));
function invCost(x){return +x.totalCost||((+x.qty||0)*(+x.buyPrice||0)+(+x.commission||0)+(+x.extraCost||0))||(+x.amount||0)}
function invTypeUnit(t){t=U(t);return ['ALTIN','GÜMÜŞ'].includes(t)?'GRAM':['DÖVİZ'].includes(t)?'MİKTAR':'ADET / MİKTAR'}
window.setFinanceTab=(t)=>{state.ui.financeTab=t;save();render()};
window.setReportRange=()=>{const f=document.querySelector('#reportFrom')?.value||'',t=document.querySelector('#reportTo')?.value||'';state.ui.reportFrom=f;state.ui.reportTo=t;save();render()};
function rangeFilter(a){let f=state.ui.reportFrom,t=state.ui.reportTo;return a.filter(x=>(!f||x.date>=f)&&(!t||x.date<=t))}
function categorySummary(arr){const t=catTotals(arr);return `<div class="v43CatGrid">${t.length?t.map(([k,v])=>`<div><span>${esc(k)}</span><b>${money(v)}</b></div>`).join(''):'<div class="notice">KAYIT YOK.</div>'}</div>`}

// Harçlık: kime verildi
const oldExpenseForm=expenseFormFor;
expenseFormFor=function(x=null){let h=oldExpenseForm(x);h=h.replace('<div class="field otherNameField"',`<div class="field allowanceNameField" style="${(x?.category==='HARÇLIK')?'':'display:none'}"><label>KİME VERİLDİ?</label><input name="recipient" value="${esc(x?.recipient||'')}" placeholder="İSİM"></div><div class="field otherNameField"`);h=h.replace('onchange="toggleOtherName(this.form)"','onchange="toggleExpenseExtras(this.form)"');return h};
window.toggleExpenseExtras=(f)=>{const v=f.querySelector('[name=category]:checked')?.value;const o=f.querySelector('.otherNameField'),a=f.querySelector('.allowanceNameField');if(o)o.style.display=v==='DİĞER'?'block':'none';if(a)a.style.display=v==='HARÇLIK'?'block':'none'};
toggleOtherName=toggleExpenseExtras;
submitExpense=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),category=d.category||'DİĞER',title=category==='DİĞER'?U(d.customTitle||'DİĞER'):category;state.expenses.push({id:uid(),date:d.date,title,customTitle:category==='DİĞER'?title:'',recipient:category==='HARÇLIK'?U(d.recipient||''):'',amount:+d.amount||0,category,method:d.method||'NAKİT',note:d.note||''});save();modal=null;screen='expenses';render()};
submitEditExpense=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),x=state.expenses.find(z=>z.id===id);if(!x)return;const old=+x.amount||0,category=d.category||'DİĞER';Object.assign(x,{date:d.date,category,title:category==='DİĞER'?U(d.customTitle||'DİĞER'):category,customTitle:category==='DİĞER'?U(d.customTitle||''):'',recipient:category==='HARÇLIK'?U(d.recipient||''):'',amount:+d.amount||0,method:d.method||'NAKİT',note:d.note||''});if(x.sourceType==='card'&&x.cardId&&x.sourceId){const c=state.cards.find(z=>z.id===x.cardId),t=c?.transactions?.find(z=>z.id===x.sourceId);if(c&&t){c.balance=(+c.balance||0)+(+x.amount-old);Object.assign(t,{title:x.title,amount:x.amount,date:x.date})}}save();closeModal();render()};
expensesScreen=function(){const a=state.expenses.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')),mo=monthItems(state.expenses);return `${header('HARCAMALAR',true)}<div class="expenseHero"><div><small>BU AY HARCAMA</small><strong class="red">${money(mo.reduce((n,x)=>n+(+x.amount||0),0))}</strong></div><button class="premiumAddBtn" onclick="openModal('expense')"><i>＋</i><span>HARCAMA EKLE</span></button></div><div class="section"><b>KATEGORİ TOPLAMLARI</b></div>${categorySummary(mo)}<div class="section"><b>HARCAMA DÖKÜMÜ</b><span>DÜZENLE / SİL</span></div><div class="card list expenseList">${a.length?a.map(x=>{const [ic,cl]=expenseMeta(x);return `<div class="item expenseItem"><div class="ico expenseIco ${cl}">${ic}</div><div><b>${esc(x.title||x.category)}</b><small>${x.date} · ${esc(x.method||'NAKİT')}${x.recipient?` · KİME: ${esc(x.recipient)}`:''}</small></div><div class="expenseRight"><div class="amt red">-${money(x.amount)}</div>${actionButtons('expense',x.id,x.date)}</div></div>`}).join(''):'<div class="notice">HENÜZ HARCAMA YOK.</div>'}</div>`};

// İş ödeme durumu + son giriş hafızası
function paymentField(x){return `<div class="field"><label>ÖDEME DURUMU</label><div class="choiceRow"><label><input type="radio" name="paid" value="yes" ${x?.paid!==false?'checked':''}>ÖDENDİ</label><label><input type="radio" name="paid" value="no" ${x?.paid===false?'checked':''}>ÖDENMEDİ</label></div></div>`}
const oldWorkScreen=workScreen;
workScreen=function(type='daily'){let h=oldWorkScreen(type);h=h.replace('<button class="primary">KAYDET</button>',paymentField(null)+'<button class="primary">KAYDET</button>');return h};
function rememberWork(d,type){state.lastEntry.date=d.date||state.lastEntry.date;if(type==='daily')state.lastEntry.dailyAmount=+d.amount||state.lastEntry.dailyAmount;if(type==='hourly')state.lastEntry.hourlyRate=+d.rate||state.lastEntry.hourlyRate;if(type==='overtime')state.lastEntry.overtimeRate=+d.rate||state.lastEntry.overtimeRate;if(d.roadAmount!==undefined)state.lastEntry.roadAmount=+d.roadAmount||state.lastEntry.roadAmount}
submitDaily=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),w={id:uid(),type:'daily',date:d.date,title:U(d.title||'ANA İŞ'),amount:+d.amount||0,paid:d.paid!=='no',note:d.note||''};state.work.push(w);syncRoad(w,d);rememberWork(d,'daily');save();closeModal();render()};
submitHourly=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),w={id:uid(),type:'hourly',date:d.date,title:U(d.title||'EK İŞ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),paid:d.paid!=='no',note:d.note||''};state.work.push(w);syncRoad(w,d);rememberWork(d,'hourly');save();closeModal();render()};
submitOvertime=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),w={id:uid(),type:'overtime',date:d.date,title:U(d.title||'MESAİ'),hours:+d.hours||0,rate:+d.rate||0,amount:(+d.hours||0)*(+d.rate||0),paid:d.paid!=='no',note:d.note||''};state.work.push(w);rememberWork(d,'overtime');save();closeModal();render()};

// Yatırım maliyet sistemi
function investmentForm(x=null){const type=U(x?.investmentType||'HİSSE'),qty=x?.qty??1,buy=x?.buyPrice??(+x?.amount||0),com=x?.commission||0,extra=x?.extraCost||0;return `<form onsubmit="submitInvestmentV43(event,'${x?.id||''}')">${field('title','YATIRIM / HİSSE ADI',esc(x?.title||''))}<div class="field"><label>YATIRIM TÜRÜ</label><select name="investmentType">${['HİSSE','FON','DÖVİZ','ALTIN','GÜMÜŞ','KRİPTO','DİĞER'].map(t=>`<option ${t===type?'selected':''}>${t}</option>`).join('')}</select></div>${field('qty',invTypeUnit(type),qty,'number')}${field('buyPrice','BİRİM ALIŞ FİYATI',buy,'number')}${field('commission','KOMİSYON',com,'number')}${field('extraCost','EKSTRA MALİYET / GİDER',extra,'number')}${field('date','ALIŞ TARİHİ',x?.date||iso(),'date')}<div class="v43CostPreview">TOPLAM MALİYET KAYDEDERKEN OTOMATİK HESAPLANIR</div><button class="primary">${x?'DEĞİŞİKLİĞİ KAYDET':'YATIRIMI KAYDET'}</button>${x?`<button type="button" class="secondary dangerBtn" onclick="deleteRecord('investment','${x.id}')">YATIRIMI SİL</button>`:''}</form>`}
window.submitInvestmentV43=(e,id='')=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),qty=+d.qty||0,buyPrice=+d.buyPrice||0,commission=+d.commission||0,extraCost=+d.extraCost||0,totalCost=qty*buyPrice+commission+extraCost,x={id:id||uid(),title:U(d.title||'YATIRIM'),investmentType:U(d.investmentType||'DİĞER'),qty,buyPrice,commission,extraCost,totalCost,amount:totalCost,date:d.date};if(id){const i=state.investments.findIndex(z=>z.id===id);if(i>=0)state.investments[i]=x}else state.investments.push(x);save();closeModal();render()};
investments=function(){const a=state.investments.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')),total=a.reduce((n,x)=>n+invCost(x),0);return `${header('YATIRIMLAR',true)}<div class="v43InvestHero"><small>TOPLAM MALİYET</small><strong>${money(total)}</strong><button onclick="openModal('investment')">＋ YATIRIM EKLE</button></div><div class="v43InvestList">${a.length?a.map(x=>`<button class="v43InvestRow" onclick="openModal('editInvestmentV43:${x.id}')"><span class="v43InvIcon">↗</span><span><b>${esc(x.title)}</b><small>${esc(x.investmentType||'YATIRIM')} · ${x.qty??1} ${invTypeUnit(x.investmentType)} · ${x.date}</small></span><strong>${money(invCost(x))}</strong><i>›</i></button>`).join(''):'<div class="notice">HENÜZ YATIRIM KAYDI YOK.</div>'}</div>`};

// Finans tek merkez
finance=function(){const tab=state.ui.financeTab||'cards';let body='';if(tab==='cards')body=`<div class="section"><b>KREDİ KARTLARIM</b><span onclick="openModal('addCard')">＋ KART EKLE</span></div>${state.cards.length?state.cards.map(c=>`<div class="v43VerticalCard" onclick="openModal('editCard:${c.id}')"><small>KREDİ KARTI</small><b>${esc(c.name)}</b><strong>${money(c.balance)}</strong><span>LİMİT ${money(c.limit)}</span></div>`).join(''):'<div class="notice">HENÜZ KART YOK.</div>'}`;if(tab==='accounts')body=`<div class="section"><b>ESNEK HESAPLARIM</b><span onclick="openModal('addFlex')">＋ HESAP EKLE</span></div>${state.flexAccounts.length?state.flexAccounts.map(c=>`<div class="v43VerticalCard flex" onclick="openModal('editFlex:${c.id}')"><small>ESNEK HESAP</small><b>${esc(c.name)}</b><strong>${money(c.balance)}</strong><span>KULLANILABİLİR ${money(Math.max(0,c.limit-c.balance))}</span></div>`).join(''):'<div class="notice">HENÜZ ESNEK HESAP YOK.</div>'}`;if(tab==='investments')body=investments().replace(header('YATIRIMLAR',true),'');return `${header('FİNANS',true)}<div class="v43FinanceTabs"><button class="${tab==='cards'?'active':''}" onclick="setFinanceTab('cards')">▰ KARTLAR</button><button class="${tab==='accounts'?'active':''}" onclick="setFinanceTab('accounts')">🏦 HESAPLAR</button><button class="${tab==='investments'?'active':''}" onclick="setFinanceTab('investments')">↗ YATIRIMLAR</button></div>${body}`};

// Takvim çoklu renk + detaylı ay özeti + swipe
calendarScreen=function(){const d=new Date(calendarCursor),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7;let cells='';for(let i=0;i<offset;i++)cells+='<div class="daySpacer"></div>';for(let n=1;n<=days;n++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),flags=[w.some(x=>x.type==='daily')?'daily':'',w.some(x=>x.type==='hourly')?'hourly':'',w.some(x=>x.type==='overtime')?'overtime':'',state.expenses.some(x=>x.date===ds)?'expense':''].filter(Boolean);cells+=`<button class="day premiumDay ${ds===iso()?'today':''}" onclick="openModal('day:${ds}')"><span class="dayNumber">${n}</span><span class="v43DayMarks">${flags.map(f=>`<i class="${f}"></i>`).join('')}</span></button>`}const p=`${y}-${String(m+1).padStart(2,'0')}`,mw=state.work.filter(x=>x.date?.startsWith(p)),me=state.expenses.filter(x=>x.date?.startsWith(p)),mi=state.incomes.filter(x=>x.date?.startsWith(p)),daysWorked=new Set(mw.filter(x=>x.type==='daily').map(x=>x.date)).size,hours=mw.filter(x=>x.type==='hourly').reduce((n,x)=>n+(+x.hours||0),0),ot=mw.filter(x=>x.type==='overtime').reduce((n,x)=>n+(+x.hours||0),0),income=mi.reduce((n,x)=>n+(+x.amount||0),0)+mw.reduce((n,x)=>n+workIncome(x),0),expense=me.reduce((n,x)=>n+(+x.amount||0),0),mn=U(d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}));return `${header('TAKVİM',true)}<div class="calendarTitleRow"><button class="calendarArrow" onclick="moveCalendar(-1)">‹</button><div><b>${mn}</b><small>SAĞA / SOLA KAYDIRARAK AY DEĞİŞTİR</small></div><button class="calendarArrow" onclick="moveCalendar(1)">›</button></div><div id="v43CalendarSwipe" class="card compactCalendar referenceCalendar"><div class="calendarHead">${['PZT','SAL','ÇAR','PER','CUM','CMT','PAZ'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar">${cells}</div><div class="calendarLegend"><span><i class="legendDaily"></i>TAM GÜN</span><span><i class="legendHourly"></i>SAATLİK</span><span><i class="legendOvertime"></i>MESAİ</span><span><i class="legendFinance"></i>HARCAMA</span></div></div><div class="v43MonthSummary"><h3>${mn} ÖZETİ</h3><div><span>ÇALIŞILAN GÜN</span><b>${daysWorked} GÜN</b></div><div><span>SAATLİK ÇALIŞMA</span><b>${hours} SAAT</b></div><div><span>TOPLAM MESAİ</span><b>${ot} SAAT</b></div><div><span>TOPLAM GELİR</span><b class="green">${money(income)}</b></div><div><span>TOPLAM HARCAMA</span><b class="red">${money(expense)}</b></div><div><span>KALAN</span><b>${money(income-expense)}</b></div></div>`};

// Rapor özel tarih aralığı ve tıklanabilir kategori dökümleri
reports=function(){const inc=rangeFilter(state.incomes),exp=rangeFilter(state.expenses),wrk=rangeFilter(state.work),income=inc.reduce((n,x)=>n+(+x.amount||0),0)+wrk.reduce((n,x)=>n+workIncome(x),0),expense=exp.reduce((n,x)=>n+(+x.amount||0),0);return `${header('RAPORLAR',true)}<div class="v43Range"><label>BAŞLANGIÇ<input id="reportFrom" type="date" value="${state.ui.reportFrom}"></label><label>BİTİŞ<input id="reportTo" type="date" value="${state.ui.reportTo}"></label><button onclick="setReportRange()">UYGULA</button></div><div class="reportGrid"><button class="reportBox" onclick="openModal('v43Income')"><small>TOPLAM GELİR</small><strong class="green">${money(income)}</strong><span>DETAY ›</span></button><button class="reportBox" onclick="openModal('v43Expense')"><small>TOPLAM HARCAMA</small><strong class="red">${money(expense)}</strong><span>KATEGORİLER ›</span></button><div class="reportBox"><small>KALAN</small><strong>${money(income-expense)}</strong></div></div><div class="section"><b>HARCAMA KATEGORİLERİ</b></div>${categorySummary(exp)}<div class="section"><b>HAREKETLER</b></div><div class="card list">${[...inc.map(x=>({...x,k:'income'})),...exp.map(x=>({...x,k:'expense'})),...wrk.map(x=>({...x,k:'work'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(x=>`<div class="item"><div class="ico">${x.k==='expense'?'₺':x.k==='work'?'✓':'＋'}</div><div><b>${esc(x.title||x.type)}</b><small>${x.date}</small></div><div class="expenseRight"><b>${money(x.k==='work'?workIncome(x):x.amount)}</b>${actionButtons(x.k,x.id,x.date)}</div></div>`).join('')||'<div class="notice">BU TARİH ARALIĞINDA KAYIT YOK.</div>'}</div>`};

// Ana ekran aylık kartları tıklanabilir
const oldHomeV43=home;home=function(){let h=oldHomeV43();h=h.replace('<div class="stat"><small>BU AY GELİR</small>','<div class="stat v43Click" onclick="openModal(\'v43MonthIncome\')"><small>BU AY GELİR</small>').replace('<div class="stat"><small>BU AY HARCAMA</small>','<div class="stat v43Click" onclick="openModal(\'v43MonthExpense\')"><small>BU AY HARCAMA</small>');h=h.replace(/onclick="go\('investments'\)"/g,"onclick=\"go('finance');setFinanceTab('investments')\"");return h};

// Parola ekranı: V42 kilit sürümündeki mevcut tasarım aynen korunur.

// Tek ikon mantığı + yatırım ana menüden çıkar, finans içine girer
nav=function(){const items=[['home','⌂','ANA SAYFA'],['work','✓','İŞ'],['expenses','₺','HARCAMA'],['calendar','31','TAKVİM'],['reports','▥','RAPOR'],['finance','▰','FİNANS'],['more','•••','DAHA FAZLA']];return `<div class="navV36">${items.map(x=>`<button class="${screen===x[0]?'active ':''}" onclick="go('${x[0]}')"><span class="navIconV36">${x[1]}</span><span class="navLabelV36">${x[2]}</span></button>`).join('')}</div>`};

modalHtml=function(k){if(k==='investment')return `<div class="modal" onclick="safeBackdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>YATIRIM EKLE</b><button class="close" onclick="closeModal()">×</button></div>${investmentForm()}</div></div>`;if(k.startsWith('editInvestmentV43:')){const x=state.investments.find(z=>z.id===k.split(':')[1]);return `<div class="modal" onclick="safeBackdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>YATIRIMI DÜZENLE</b><button class="close" onclick="closeModal()">×</button></div>${x?investmentForm(x):''}</div></div>`}if(k==='v43Expense'||k==='v43MonthExpense'){const a=k.includes('Month')?monthItems(state.expenses):rangeFilter(state.expenses);return `<div class="modal" onclick="safeBackdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>HARCAMA DÖKÜMÜ</b><button class="close" onclick="closeModal()">×</button></div>${categorySummary(a)}<div class="card list">${a.map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${x.date}${x.recipient?` · KİME: ${esc(x.recipient)}`:''}</small></div><div class="expenseRight"><b class="red">${money(x.amount)}</b>${actionButtons('expense',x.id,x.date)}</div></div>`).join('')}</div></div></div>`}if(k==='v43Income'||k==='v43MonthIncome'){const mi=k.includes('Month'),a=mi?monthItems(state.incomes):rangeFilter(state.incomes),w=mi?monthItems(state.work):rangeFilter(state.work);const groups=[['GÜNLÜK İŞ',w.filter(x=>x.type==='daily').reduce((n,x)=>n+workIncome(x),0)],['SAATLİK İŞ',w.filter(x=>x.type==='hourly').reduce((n,x)=>n+workIncome(x),0)],['MESAİ',w.filter(x=>x.type==='overtime').reduce((n,x)=>n+workIncome(x),0)],['DİĞER GELİR',a.reduce((n,x)=>n+(+x.amount||0),0)]];return `<div class="modal" onclick="safeBackdropClose(event)"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>GELİR DÖKÜMÜ</b><button class="close" onclick="closeModal()">×</button></div><div class="v43CatGrid">${groups.map(([n,v])=>`<div><span>${n}</span><b>${money(v)}</b></div>`).join('')}</div><div class="card list">${[...w.map(x=>({...x,k:'work'})),...a.map(x=>({...x,k:'income'}))].map(x=>`<div class="item"><div><b>${esc(x.title||x.type)}</b><small>${x.date}</small></div><div class="expenseRight"><b class="green">${money(x.k==='work'?workIncome(x):x.amount)}</b>${actionButtons(x.k,x.id,x.date)}</div></div>`).join('')}</div></div></div>`}let h=oldModalV43(k);if(k==='daily'||k.startsWith('dailyDate:')||k==='hourly'||k.startsWith('hourlyDate:')||k==='overtime'||k.startsWith('overtimeDate:'))h=h.replace('<button class="primary">KAYDET</button>',paymentField(null)+'<button class="primary">KAYDET</button>');if(k.startsWith('editRecord:work:')){const id=k.split(':')[2],x=state.work.find(z=>z.id===id);h=h.replace('<button class="primary">DEĞİŞİKLİĞİ KAYDET</button>',paymentField(x)+'<button class="primary">DEĞİŞİKLİĞİ KAYDET</button>')}return h};
const oldEditWorkV43=submitEditWork;submitEditWork=function(e,id,fromDs=''){const d=Object.fromEntries(new FormData(e.currentTarget).entries()),w=state.work.find(x=>x.id===id);if(w)w.paid=d.paid!=='no';return oldEditWorkV43(e,id,fromDs)};

// render sonrası swipe bağla
const renderV43=render;render=function(){renderV43();requestAnimationFrame(()=>{const el=document.querySelector('#v43CalendarSwipe');if(el&&!el.dataset.swipe){el.dataset.swipe='1';let sx=0;el.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>55)moveCalendar(dx<0?1:-1)},{passive:true})}})};
render();
})();
