/* RUTIN V46 — V42 base + requested items 1–17 only */
(function(){
'use strict';
const H=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>Number(v)||0, amt=x=>num(x.amount), workAmt=x=>num(x.amount)||(num(x.hours)*num(x.rate));
const pref=()=>`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}`;
const inRange=(d,a,b)=>String(d||'')>=a&&String(d||'')<=b;
state.uiMemory=state.uiMemory||{work:{date:iso(),dailyAmount:state.settings.dailyRate||0,hourlyRate:state.settings.hourlyRate||0,overtimeRate:state.settings.overtimeRate||0,roadAmount:0}};
state.investments=(state.investments||[]).map(x=>({...x,qty:num(x.qty||1),buyPrice:num(x.buyPrice||x.amount||0),commission:num(x.commission),extraCost:num(x.extraCost),amount:num(x.totalCost||x.amount||0),assetType:x.assetType||'HİSSE'}));

function paidField(x){return `<div class="field"><label>ÖDEME DURUMU</label><div class="choiceRow"><label><input type="radio" name="paid" value="yes" ${x?.paid!==false?'checked':''}>ÖDENDİ</label><label><input type="radio" name="paid" value="no" ${x?.paid===false?'checked':''}>ÖDENMEDİ</label></div></div>`}
function workForm(type,x=null){const M=state.uiMemory.work||{}, date=x?.date||M.date||iso(), road=state.expenses.find(e=>e.workId===x?.id||e.sourceWorkId===x?.id); const roadAmt=road?.amount??M.roadAmount??0;
 const common=`${field('date','TARİH',date,'date')}${field('title','İŞ / PROJE',x?.title||(type==='hourly'?'EK İŞ':'ANA İŞ'))}`;
 const roadFields=type==='overtime'?'':`<div class="field"><label>YOL PARASI</label><div class="choiceRow"><label><input type="radio" name="road" value="yes" ${road?'checked':''}>ÖDEDİM</label><label><input type="radio" name="road" value="no" ${road?'':'checked'}>ÖDEMEDİM</label></div></div>${field('roadAmount','YOL TUTARI (OPSİYONEL)',roadAmt,'number')}`;
 const body=type==='daily'?field('amount','GÜNLÜK ÜCRET',x?.amount??M.dailyAmount??state.settings.dailyRate,'number'):field('hours',type==='hourly'?'KAÇ SAAT ÇALIŞTIN?':'MESAİ SÜRESİ',x?.hours||0,'number')+field('rate',type==='hourly'?'SAATLİK ÜCRET':'MESAİ SAATLİK ÜCRET',x?.rate??(type==='hourly'?M.hourlyRate:M.overtimeRate),'number');
 return `<form onsubmit="saveWorkV46(event,'${type}','${x?.id||''}')">${common}${body}${roadFields}${paidField(x)}<div class="field"><label>NOT</label><textarea name="note">${H(x?.note||'')}</textarea></div><button class="primary">${x?'DEĞİŞİKLİĞİ KAYDET':'KAYDET'}</button></form>`;
}
dailyForm=()=>workForm('daily'); hourlyForm=()=>workForm('hourly'); overtimeForm=()=>workForm('overtime');
window.saveWorkV46=function(e,type,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()), old=id?state.work.find(x=>x.id===id):null, w=old||{id:uid(),type};
 Object.assign(w,{type,date:d.date,title:upper(d.title||'İŞ'),note:d.note||'',paid:d.paid!=='no'}); if(type==='daily')w.amount=num(d.amount);else{w.hours=num(d.hours);w.rate=num(d.rate);w.amount=w.hours*w.rate}
 if(!old)state.work.push(w); const M=state.uiMemory.work;M.date=d.date;if(type==='daily')M.dailyAmount=num(d.amount);if(type==='hourly')M.hourlyRate=num(d.rate);if(type==='overtime')M.overtimeRate=num(d.rate);if(type!=='overtime')M.roadAmount=num(d.roadAmount);
 if(type!=='overtime'){let r=state.expenses.find(z=>z.workId===w.id||z.sourceWorkId===w.id);if(d.road==='yes'&&num(d.roadAmount)>0){if(!r){r={id:uid(),workId:w.id,sourceWorkId:w.id,category:'YOL',title:'YOL',method:'NAKİT',note:'ÇALIŞMA YOL MASRAFI'};state.expenses.push(r)}Object.assign(r,{date:d.date,amount:num(d.roadAmount)})}else if(r)state.expenses=state.expenses.filter(z=>z.id!==r.id)} save();modal=null;render();}

function catTotals(items){const o={};items.forEach(x=>{const c=upper(x.category||'DİĞER');o[c]=(o[c]||0)+amt(x)});return Object.entries(o).sort((a,b)=>b[1]-a[1])}
const oldExpensesScreen=expensesScreen;
expensesScreen=function(){const mm=state.expenses.filter(x=>String(x.date||'').startsWith(pref())), cats=catTotals(mm);return oldExpensesScreen()+`<div class="section"><b>KATEGORİ TOPLAMLARI</b><span>${cats.length} KATEGORİ</span></div><div class="card list v46CatTotals">${cats.map(([c,n])=>`<button class="v46ListBtn" onclick="openModal('categoryDetail:${encodeURIComponent(c)}')"><span>${H(c)}</span><strong>${money(n)}</strong><b>›</b></button>`).join('')||'<div class="notice">KAYIT YOK.</div>'}</div>`}

function dayDetail(ds){const w=state.work.filter(x=>x.date===ds), ex=state.expenses.filter(x=>x.date===ds), inc=state.incomes.filter(x=>x.date===ds), cats=catTotals(ex), wh=w.filter(x=>x.type==='hourly').reduce((a,x)=>a+num(x.hours),0), ot=w.filter(x=>x.type==='overtime').reduce((a,x)=>a+num(x.hours),0);
 return `<div class="daySwipeHead"><button onclick="shiftDay('${ds}',-1)">‹</button><div><b>${new Date(ds+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()}</b><small>SAĞA / SOLA KAYDIR</small></div><button onclick="shiftDay('${ds}',1)">›</button></div><div class="dayDetailTotals">${sumRow('TAM GÜN',w.filter(x=>x.type==='daily').length+' GÜN')}${sumRow('SAATLİK',wh+' SAAT')}${sumRow('MESAİ',ot+' SAAT')}${sumRow('GELİR',money(inc.reduce((a,x)=>a+amt(x),0)+w.reduce((a,x)=>a+workAmt(x),0)))}${sumRow('HARCAMA',money(ex.reduce((a,x)=>a+amt(x),0)))}</div>${cats.length?`<div class="section"><b>HARCAMA KATEGORİLERİ</b></div><div class="card list">${cats.map(([c,n])=>sumRow(c,money(n))).join('')}</div>`:''}<div class="section"><b>ÇALIŞMA</b></div>${w.map(x=>`<div class="detailRecord"><div><b>${H(x.title)}</b><small>${x.type.toUpperCase()}${x.hours?' · '+x.hours+' SAAT':''} · ${x.paid===false?'ÖDENMEDİ':'ÖDENDİ'}</small></div><strong>${money(workAmt(x))}</strong><button onclick="openModal('editWorkV46:${x.id}:${ds}')">DÜZENLE</button><button onclick="deleteRecord('work','${x.id}','${ds}')">SİL</button></div>`).join('')||'<div class="notice">ÇALIŞMA YOK.</div>'}<div class="section"><b>HARCAMALAR</b></div>${ex.map(x=>`<div class="detailRecord"><div><b>${H(x.title||x.category)}</b><small>${H(x.category||'DİĞER')}${x.recipient?' · '+H(x.recipient):''}</small></div><strong class="red">-${money(x.amount)}</strong><button onclick="openModal('editRecord:expense:${x.id}:${ds}')">DÜZENLE</button><button onclick="deleteRecord('expense','${x.id}','${ds}')">SİL</button></div>`).join('')||'<div class="notice">HARCAMA YOK.</div>'}<div class="section"><b>GELİRLER</b></div>${inc.map(x=>`<div class="detailRecord"><div><b>${H(x.title)}</b><small>${x.date}</small></div><strong class="green">${money(x.amount)}</strong><button onclick="deleteRecord('income','${x.id}','${ds}')">SİL</button></div>`).join('')||'<div class="notice">GELİR YOK.</div>'}`}

const oldModalV46=modalHtml;
modalHtml=function(k){if(k.startsWith('day:'))return `<div class="modal v18Modal" onclick="safeBackdropClose(event)"><div class="sheet v18Sheet" data-day="${k.slice(4)}" onclick="event.stopPropagation()"><div class="sheetHead"><b>GÜN DETAYI</b><button class="close" onclick="closeModal()">×</button></div>${dayDetail(k.slice(4))}</div></div>`;
 if(k.startsWith('editWorkV46:')){const p=k.split(':'),x=state.work.find(z=>z.id===p[1]);return `<div class="modal"><div class="sheet" onclick="event.stopPropagation()"><div class="sheetHead"><b>ÇALIŞMAYI DÜZENLE</b><button class="close" onclick="closeModal()">×</button></div>${x?workForm(x.type,x):''}</div></div>`}
 if(k==='rangeV46'){return `<div class="modal"><div class="sheet"><div class="sheetHead"><b>TARİH ARALIĞI</b><button class="close" onclick="closeModal()">×</button></div><form onsubmit="applyRangeV46(event)">${field('start','BAŞLANGIÇ',window.reportRangeV46?.start||`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}-01`,'date')}${field('end','BİTİŞ',window.reportRangeV46?.end||iso(),'date')}<button class="primary">UYGULA</button></form></div></div>`}
 if(k.startsWith('reportBreakV46:')){const kind=k.split(':')[1], rr=reportDatesV46(), arr=kind==='expense'?state.expenses:kind==='income'?state.incomes:state.work, items=arr.filter(x=>inRange(x.date,rr.start,rr.end));const groups={};items.forEach(x=>{const key=kind==='expense'?upper(x.category||'DİĞER'):kind==='income'?upper(x.title||'DİĞER'):x.type==='daily'?'GÜNLÜK':x.type==='hourly'?'SAATLİK':'MESAİ';groups[key]=(groups[key]||0)+(kind==='work'?workAmt(x):amt(x))});return `<div class="modal"><div class="sheet"><div class="sheetHead"><b>${kind==='expense'?'HARCAMA':'GELİR'} AYRINTISI</b><button class="close" onclick="closeModal()">×</button></div><div class="card list">${Object.entries(groups).map(([a,b])=>sumRow(a,money(b))).join('')||'<div class="notice">KAYIT YOK.</div>'}</div>${items.map(x=>`<div class="detailRecord"><div><b>${H(x.title||x.type)}</b><small>${x.date}${x.category?' · '+H(x.category):''}</small></div><strong>${money(kind==='work'?workAmt(x):x.amount)}</strong>${kind==='expense'?`<button onclick="openModal('editRecord:expense:${x.id}:${x.date}')">DÜZENLE</button><button onclick="deleteRecord('expense','${x.id}')">SİL</button>`:''}</div>`).join('')}</div></div>`}
 if(k.startsWith('periodDetail:')){const t=k.split(':')[1],today=t.startsWith('today'),income=t.endsWith('Income'), base=income?state.incomes:state.expenses, direct=base.filter(x=>today?x.date===iso():String(x.date||'').startsWith(pref())), works=income?state.work.filter(x=>today?x.date===iso():String(x.date||'').startsWith(pref())):[], total=direct.reduce((a,x)=>a+amt(x),0)+works.reduce((a,x)=>a+workAmt(x),0), cats=!income?catTotals(direct):[];return `<div class="modal"><div class="sheet"><div class="sheetHead"><b>${income?'GELİR':'HARCAMA'} AYRINTISI</b><button class="close" onclick="closeModal()">×</button></div><div class="analysisHero"><small>TOPLAM</small><strong>${money(total)}</strong></div>${cats.map(([c,n])=>sumRow(c,money(n))).join('')}${works.map(x=>`<div class="detailRecord"><div><b>${H(x.title)}</b><small>${x.type.toUpperCase()} · ${x.date}</small></div><strong>${money(workAmt(x))}</strong><button onclick="openModal('editWorkV46:${x.id}:${x.date}')">DÜZENLE</button><button onclick="deleteRecord('work','${x.id}')">SİL</button></div>`).join('')}${direct.map(x=>`<div class="detailRecord"><div><b>${H(x.title||x.category)}</b><small>${x.date}${x.recipient?' · '+H(x.recipient):''}</small></div><strong>${money(x.amount)}</strong><button onclick="openModal('editRecord:${income?'income':'expense'}:${x.id}:${x.date}')">DÜZENLE</button><button onclick="deleteRecord('${income?'income':'expense'}','${x.id}')">SİL</button></div>`).join('')}</div></div>`}
 if(k==='investment'||k.startsWith('investmentV46:')){const id=k.split(':')[1]||'',x=state.investments.find(z=>z.id===id);return `<div class="modal"><div class="sheet"><div class="sheetHead"><b>${x?'YATIRIMI DÜZENLE':'YATIRIM EKLE'}</b><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveInvestmentV46(event,'${id}')">${field('title','YATIRIM / HİSSE ADI',x?.title||'')}${field('qty','ADET / GRAM / MİKTAR',x?.qty||1,'number')}${field('buyPrice','BİRİM ALIŞ FİYATI',x?.buyPrice||0,'number')}${field('commission','KOMİSYON',x?.commission||0,'number')}${field('extraCost','EKSTRA MALİYET / GİDER',x?.extraCost||0,'number')}${field('date','ALIŞ TARİHİ',x?.date||iso(),'date')}<button class="primary">KAYDET</button>${x?`<button type="button" class="secondary" onclick="deleteRecord('investment','${x.id}')">YATIRIMI SİL</button>`:''}</form></div></div>`}
 return oldModalV46(k)};
window.applyRangeV46=function(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());window.reportRangeV46={start:d.start,end:d.end};reportPeriod='rangeV46';closeModal();render()}
function reportDatesV46(){if(reportPeriod==='rangeV46'&&window.reportRangeV46)return window.reportRangeV46;const r=dateRangeForPeriod(reportPeriod==='rangeV46'?'month':reportPeriod);return {start:r.start?iso(r.start):r.from||`${pref()}-01`,end:r.end?iso(r.end):r.to||iso()}}
const oldReportsV46=reports;
reports=function(){let h=oldReportsV46().replace(/onclick="openModal\('range'\)"/g,"onclick=\"openModal('rangeV46')\"");const rr=reportDatesV46(), ex=state.expenses.filter(x=>inRange(x.date,rr.start,rr.end)), inc=state.incomes.filter(x=>inRange(x.date,rr.start,rr.end)), wk=state.work.filter(x=>inRange(x.date,rr.start,rr.end));if(reportPeriod==='rangeV46'){const ti=inc.reduce((a,x)=>a+amt(x),0)+wk.reduce((a,x)=>a+workAmt(x),0),te=ex.reduce((a,x)=>a+amt(x),0);h=h.replace(/<div class="reportGrid">[\s\S]*?<\/div>\s*\n\s*<div class="section"><b>GELİR \/ HARCAMA DAĞILIMI/,`<div class="reportGrid"><div class="reportBox"><small>TOPLAM GELİR</small><strong class="green">${money(ti)}</strong></div><div class="reportBox"><small>TOPLAM HARCAMA</small><strong class="red">${money(te)}</strong></div><div class="reportBox"><small>NET KAZANÇ</small><strong>${money(ti-te)}</strong></div></div><div class="section"><b>GELİR / HARCAMA DAĞILIMI`)}return h+`<div class="section"><b>KATEGORİ / TÜR AYRINTISI</b></div><div class="v46ReportBtns"><button onclick="openModal('reportBreakV46:income')">GELİR TÜRLERİ</button><button onclick="openModal('reportBreakV46:expense')">HARCAMA KATEGORİLERİ</button></div>`}

window.saveInvestmentV46=function(e,id){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),qty=num(d.qty),buy=num(d.buyPrice),comm=num(d.commission),extra=num(d.extraCost),total=qty*buy+comm+extra,x=id?state.investments.find(z=>z.id===id):{id:uid()};Object.assign(x,{title:upper(d.title||'YATIRIM'),qty,buyPrice:buy,commission:comm,extraCost:extra,totalCost:total,amount:total,date:d.date,assetType:'YATIRIM'});if(!id)state.investments.push(x);save();modal=null;screen='finance';window.financeTabV42='investments';render()}
function investmentPanel(){const a=state.investments.slice().sort((x,y)=>String(y.date).localeCompare(String(x.date))),total=a.reduce((n,x)=>n+num(x.totalCost||x.amount),0);return `<div class="investmentHeroV46"><small>TOPLAM MALİYET</small><strong>${money(total)}</strong><button onclick="openModal('investment')">＋ YATIRIM EKLE</button></div><div class="investmentListV46">${a.map(x=>`<button class="investmentRowV46" onclick="openModal('investmentV46:${x.id}')"><div><b>${H(x.title)}</b><small>${num(x.qty)} MİKTAR · ALIŞ ${money(x.buyPrice)} · ${x.date}</small></div><div><small>KOMİSYON + GİDER ${money(num(x.commission)+num(x.extraCost))}</small><strong>${money(x.totalCost||x.amount)}</strong></div><span>›</span></button>`).join('')||'<div class="notice">HENÜZ YATIRIM YOK.</div>'}</div>`}
const financeV42=finance;
finance=function(){const tab=window.financeTabV42||'cards';let h=financeV42();h=h.replace(/<div class="financeTabs42">[\s\S]*?<\/div>\s*<div class="financeTabBody42">/,`<div class="financeTabs42"><button class="${tab==='cards'?'active':''}" onclick="window.financeTabV42='cards';render()"><i>▰</i><span>KARTLAR</span></button><button class="${tab==='accounts'?'active':''}" onclick="window.financeTabV42='accounts';render()"><i>◇</i><span>HESAPLAR</span></button><button class="${tab==='investments'?'active':''}" onclick="window.financeTabV42='investments';render()"><i>↗</i><span>YATIRIMLAR</span></button></div><div class="financeTabBody42">`);if(tab==='investments')h=h.replace(/<div class="financeTabBody42">[\s\S]*?<\/div>\s*<\/div>\s*$/,`<div class="financeTabBody42">${investmentPanel()}</div></div>`);return h}
investments=function(){window.financeTabV42='investments';return finance()}

const oldCalendarV46=calendarScreen;
calendarScreen=function(){const d=new Date(calendarCursor),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),off=(new Date(y,m,1).getDay()+6)%7;let cells='<div class="emptyDay"></div>'.repeat(off);for(let n=1;n<=days;n++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,w=state.work.filter(x=>x.date===ds),types=[];if(w.some(x=>x.type==='daily'))types.push('daily');if(w.some(x=>x.type==='hourly'))types.push('hourly');if(w.some(x=>x.type==='overtime'))types.push('overtime');if(state.expenses.some(x=>x.date===ds))types.push('expense');cells+=`<button class="day premiumDay ${ds===iso()?'today':''}" onclick="openModal('day:${ds}')"><span class="dayNumber">${n}</span><span class="multiMarks">${types.map(t=>`<i class="mark-${t}"></i>`).join('')}</span></button>`}const p=`${y}-${String(m+1).padStart(2,'0')}`,mw=state.work.filter(x=>String(x.date).startsWith(p)),me=state.expenses.filter(x=>String(x.date).startsWith(p)),mi=state.incomes.filter(x=>String(x.date).startsWith(p)),daily=new Set(mw.filter(x=>x.type==='daily').map(x=>x.date)).size,hh=mw.filter(x=>x.type==='hourly').reduce((a,x)=>a+num(x.hours),0),oh=mw.filter(x=>x.type==='overtime').reduce((a,x)=>a+num(x.hours),0),income=mi.reduce((a,x)=>a+amt(x),0)+mw.reduce((a,x)=>a+workAmt(x),0),expense=me.reduce((a,x)=>a+amt(x),0),mn=d.toLocaleDateString('tr-TR',{month:'long',year:'numeric'}).toUpperCase();return `${header('TAKVİM',true)}<button class="dateJumpMini" onclick="openModal('dateJump')">◉ HIZLI AY / YIL SEÇ</button><div class="calendarTitleRow premiumMonthRow"><button class="calendarArrow" onclick="moveCalendar(-1)">‹</button><div><b>${mn}</b><small>GÜNE DOKUN · DETAYI AÇ</small></div><button class="calendarArrow" onclick="moveCalendar(1)">›</button></div><div class="card compactCalendar premiumCalendarCard"><div class="calendarHead">${['PZT','SAL','ÇAR','PER','CUM','CMT','PAZ'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar premiumCalendarGrid">${cells}</div><div class="calendarLegend premiumLegend"><span><i class="legendDaily"></i>TAM GÜN</span><span><i class="legendHourly"></i>SAATLİK</span><span><i class="legendOvertime"></i>MESAİ</span><span><i class="legendFinance"></i>HARCAMA</span></div></div><div class="section"><b>${mn} ÖZETİ</b></div><div class="calendarGoldSummary">${sumRow('TOPLAM ÇALIŞILAN GÜN',daily+' GÜN')}${sumRow('TOPLAM SAATLİK ÇALIŞMA',hh+' SAAT')}${sumRow('TOPLAM MESAİ',oh+' SAAT')}${sumRow('TOPLAM GELİR',money(income))}${sumRow('TOPLAM HARCAMA',money(expense))}${sumRow('KALAN',money(income-expense))}</div>`}
let calX=0;document.addEventListener('touchstart',e=>{if(screen==='calendar'&&!modal)calX=e.changedTouches[0].clientX},{passive:true});document.addEventListener('touchend',e=>{if(screen==='calendar'&&!modal){const dx=e.changedTouches[0].clientX-calX;if(Math.abs(dx)>65)moveCalendar(dx<0?1:-1)}},{passive:true});

save();
})();
